// Strumento 01 — Costi d'acquisto a confronto. Testi in quattro lingue.
import type { Lingua } from "@/lib/rotte";
import { fmtEuro, fmtPct, fmtNum } from "@/lib/strumenti/formato";
import { ESTERO, IT } from "@/lib/strumenti/regole";
import type { Paese } from "@/lib/strumenti/calcoli";

type P = Record<string, number>;
export type TestoVoce = { nome: (p: P) => string; spieg: (p: P) => string; breve: string; chi: string };

export type TestiCosti = {
  titolo: string; descrizione: string; h1: string; lead: string;
  prezzo: string; scala: string; esempi: string; ipotesi: string;
  venditore: string; venditori: { privato: string; impresa: string };
  casa: string; case: { seconda: string; prima: string }; primaAiuto: string; lusso: string; lussoAiuto: string;
  base: string; basi: { catastale: string; prezzo: string }; baseAiuto: string;
  rendita: string; renditaEsempio: string; renditaAiuto: string;
  agenzia: string; agenziaAiuto: string; pct: string; pctTesto: (pct: string, iva: string) => string;
  paesi: Record<Paese, string>; paesiBreve: Record<Paese, string>;
  delPrezzo: (pct: string) => string; piuInVerifica: string; soloVerifica: string;
  gruppi: { imposte: string; registri: string; agenzia: string; verifica: string };
  dettaglioCaption: (paese: string, prezzo: string) => string; totaleRiga: string;
  nessuna: string; mancaRendita: string; chf: string; ivaNota: string;
  voci: Record<string, TestoVoce>;
  annuncio: (righe: string[]) => string;
  metodo: (l: Lingua) => string[]; guidaLink: string;
  tabTitolo: string; tabCaption: string; tabPrezzo: string; tabIpotesi: string; ipotesiPaese: Record<Paese, string>; tabNota: string;
};

const pc = (n: number, l: Lingua) => fmtPct(n, l);

export const COSTI: Record<Lingua, TestiCosti> = {
  it: {
    titolo: "Costi d'acquisto sul lago d'Orta: Italia, Svizzera, Germania, Austria",
    descrizione: "Calcolatore dei costi di chi compra casa sul lago d'Orta: imposta di registro, ipotecaria e catastale, IVA, provvigione, confrontate con Canton Zurigo, Baviera e Austria. Con fonti e date.",
    h1: "Quanto costa comprare, oltre al prezzo.",
    lead: "La stessa casa, lo stesso prezzo, quattro paesi. Imposte, notaio e registri, agenzia: le voci che paga chi compra, ognuna con la sua fonte. In Italia, da un privato, le imposte si possono calcolare sul valore catastale invece che sul prezzo.",
    prezzo: "Prezzo della casa", scala: "Prezzo, su scala logaritmica", esempi: "Prezzi d'esempio", ipotesi: "Le vostre ipotesi, in Italia",
    venditore: "Chi vende", venditori: { privato: "un privato", impresa: "un'impresa, con IVA" },
    casa: "La casa sarà", case: { seconda: "seconda casa", prima: "prima casa" },
    primaAiuto: `Per l'agevolazione prima casa chi non risiede nel comune deve trasferirci la residenza entro ${IT.mesiResidenza} mesi, dichiarandolo nell'atto.`,
    lusso: "Categoria catastale A/1, A/8 o A/9", lussoAiuto: "Le abitazioni signorili, le ville e i castelli non hanno l'agevolazione prima casa; da impresa pagano l'IVA al 22%.",
    base: "Base delle imposte", basi: { catastale: "valore catastale (prezzo-valore)", prezzo: "prezzo dichiarato" },
    baseAiuto: "Il prezzo-valore vale tra persone fisiche, per abitazioni e pertinenze, e si chiede al notaio nell'atto. Il prezzo vero va comunque scritto.",
    rendita: "Rendita catastale", renditaEsempio: "È una rendita d'esempio, non un dato: scrivete quella della visura catastale.", renditaAiuto: "La trovate nella visura catastale della casa.",
    agenzia: "Con agenzia", agenziaAiuto: "In provincia di Novara l'uso raccolto dalla Camera di Commercio è il 3% per ciascuna parte, più IVA 22%. È un uso del 2005, non un tetto di legge: conta l'accordo firmato.",
    pct: "Provvigione del compratore", pctTesto: (p, i) => `${p} + IVA ${i}`,
    paesi: { it: "Italia · lago d'Orta", ch: "Svizzera · Canton Zurigo", de: "Germania · Baviera", at: "Austria" },
    paesiBreve: { it: "Italia", ch: "Svizzera", de: "Germania", at: "Austria" },
    delPrezzo: (p) => `${p} del prezzo`, piuInVerifica: "più, in verifica:", soloVerifica: "in verifica",
    gruppi: { imposte: "Imposte", registri: "Notaio e registri", agenzia: "Agenzia", verifica: "In verifica" },
    dettaglioCaption: (paese, prezzo) => `Costi di chi compra, ${paese}, per una casa da ${prezzo}`, totaleRiga: "Totale per chi compra",
    nessuna: "nessuna", mancaRendita: "serve la rendita",
    chf: "In Svizzera tariffe e minimi sono in franchi: le applichiamo allo stesso importo, senza cambio. Il confronto vale in percentuale del prezzo.",
    ivaNota: "Da impresa calcoliamo l'IVA sul prezzo come costo in più: controllate se il prezzo chiesto è «più IVA» o «IVA compresa».",
    voci: {
      registro: { nome: (p) => `Imposta di registro, ${pc(p.aliq, "it")}`, spieg: () => "Sul valore catastale: scrivete la rendita per calcolarla.", breve: "imposta di registro", chi: "chi compra" },
      registroCatastale: { nome: (p) => `Imposta di registro, ${pc(p.aliq, "it")}`, spieg: (p) => `Sul valore catastale di ${fmtEuro(p.vc, "it")} (rendita × 1,05 × moltiplicatore), minimo ${fmtEuro(p.min, "it")}.`, breve: "imposta di registro", chi: "chi compra" },
      registroPrezzo: { nome: (p) => `Imposta di registro, ${pc(p.aliq, "it")}`, spieg: (p) => `Sul prezzo dichiarato, minimo ${fmtEuro(p.min, "it")}.`, breve: "imposta di registro", chi: "chi compra" },
      ipocatastali: { nome: () => "Imposte ipotecaria e catastale", spieg: (p) => `${fmtEuro(p.ip, "it")} + ${fmtEuro(p.cat, "it")}, fisse, nella vendita da privato.`, breve: "ipotecaria e catastale", chi: "chi compra" },
      iva: { nome: (p) => `IVA, ${pc(p.aliq, "it")}`, spieg: () => "Sulla vendita da impresa: 4% prima casa, 10% altre abitazioni, 22% per A/1, A/8, A/9.", breve: "IVA", chi: "chi compra" },
      fisse: { nome: () => "Registro, ipotecaria e catastale", spieg: (p) => `${fmtEuro(p.una, "it")} ciascuna, fisse, nella vendita con IVA.`, breve: "imposte fisse", chi: "chi compra" },
      notaio: { nome: () => "Notaio", spieg: () => "Non esiste una tariffa: dal 2012 il compenso si concorda, con un preventivo. Per uso lo sceglie e lo paga chi compra.", breve: "notaio", chi: "chi compra" },
      agenzia: { nome: (p) => `Provvigione, ${pc(p.pct, "it")} + IVA ${pc(p.iva, "it")}`, spieg: () => "Uso della provincia di Novara: 3% per parte, salvo patto diverso.", breve: "provvigione", chi: "chi compra" },
      chHand: { nome: () => "Imposta sul trapasso (Handänderungssteuer)", spieg: () => "Il Canton Zurigo non la applica: è uno dei sei cantoni senza.", breve: "imposta sul trapasso", chi: "—" },
      chBeurk: { nome: (p) => `Atto pubblico (Beurkundung), ${fmtNum(p.pm, "it")}‰`, spieg: (p) => `Del valore venale, minimo ${fmtNum(p.min, "it")} CHF. Spesso divisa fra le parti per contratto.`, breve: "atto pubblico", chi: "per contratto" },
      chGrundbuch: { nome: (p) => `Registro fondiario (Grundbuch), ${fmtNum(p.pm, "it")}‰`, spieg: (p) => `Del valore venale, minimo ${fmtNum(p.min, "it")} CHF, più IVA svizzera su una parte (non sommata).`, breve: "registro fondiario", chi: "per contratto" },
      makler: { nome: () => "Provvigione", spieg: () => "Non abbiamo trovato una fonte ufficiale su quanto ne paghi chi compra: in verifica.", breve: "provvigione", chi: "—" },
      deGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "it")}`, spieg: () => "Imposta sull'acquisto: in Baviera l'aliquota federale, la più bassa in Germania.", breve: "Grunderwerbsteuer", chi: "chi compra" },
      deNotar: { nome: () => "Notaio e Grundbuch", spieg: () => "Tariffa di legge degressiva (GNotKG): non l'abbiamo ancora riletta, quindi non la sommiamo.", breve: "notaio e Grundbuch", chi: "chi compra" },
      atGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "it")}`, spieg: () => "Imposta sull'acquisto, sul prezzo.", breve: "Grunderwerbsteuer", chi: "chi compra" },
      atEintragung: { nome: (p) => `Iscrizione nel Grundbuch, ${pc(p.aliq, "it")}`, spieg: (p) => `Del valore, più ${fmtEuro(p.eingabe, "it")} di diritto di domanda.`, breve: "Grundbuch", chi: "chi compra" },
      atNotar: { nome: () => "Contratto, notaio o avvocato, fiduciario", spieg: () => "Nessuna tariffa riletta: in verifica.", breve: "contratto e fiduciario", chi: "chi compra" },
    },
    annuncio: (r) => r.join("; "),
    metodo: (l) => [
      `Italia, da un privato: imposta di registro ${pc(IT.registro, l)}, oppure ${pc(IT.registroPrima, l)} con la prima casa, con un minimo di ${fmtEuro(IT.registroMin, l)}; imposte ipotecaria e catastale fisse, ${fmtEuro(IT.ipotecaria, l)} + ${fmtEuro(IT.catastale, l)}. Col prezzo-valore la base è il valore catastale: rendita × ${fmtNum(1 + IT.rivalutazione / 100, l, 2)} × ${IT.moltiplicatore}, oppure × ${IT.moltiplicatorePrima} con la prima casa. Senza la rendita la voce resta fuori dal totale.`,
      `Italia, da un'impresa: IVA ${pc(IT.ivaPrima, l)} sulla prima casa, ${pc(IT.ivaAltre, l)} sulle altre abitazioni, ${pc(IT.ivaLusso, l)} su A/1, A/8 e A/9; registro, ipotecaria e catastale fisse, ${fmtEuro(IT.fisseImpresa, l)} ciascuna. La provvigione segue l'uso della provincia di Novara, ${pc(IT.agenzia.pct, l)} per parte più IVA ${pc(IT.agenzia.iva, l)}; il notaio non ha tariffa e resta «in verifica».`,
      `Svizzera, Canton Zurigo: nessuna imposta sul trapasso; atto pubblico e registro fondiario ${fmtNum(ESTERO.ch.beurkundungPm, l)}‰ ciascuno del valore, minimo ${ESTERO.ch.minimo} CHF. Germania, Baviera: Grunderwerbsteuer ${pc(ESTERO.de.grest, l)}; notaio e Grundbuch in verifica. Austria: Grunderwerbsteuer ${pc(ESTERO.at.grest, l)}, iscrizione nel Grundbuch ${pc(ESTERO.at.eintragung, l)} più ${fmtEuro(ESTERO.at.eingabe, l)}; contratto e fiduciario in verifica.`,
      "Fuori dall'Italia non sommiamo la provvigione: non abbiamo trovato una fonte ufficiale che dica quanto ne paga chi compra. Per questo l'interruttore «Con agenzia» cambia solo la riga italiana.",
      "Quando una voce passa da «in verifica» a verificata, il calcolatore la somma da solo: la regola sta in un file di dati con fonte e data, non nel codice. I totali con voci mancanti si leggono come «almeno».",
    ],
    guidaLink: "La guida ai costi d'acquisto a confronto",
    tabTitolo: "Tre prezzi, quattro paesi", tabCaption: "Costi di chi compra una casa da un privato, a tre prezzi d'esempio", tabPrezzo: "Prezzo", tabIpotesi: "Le ipotesi della tabella",
    ipotesiPaese: {
      it: "Seconda casa da privato col prezzo-valore e una rendita d'esempio di 2.000 €, provvigione 3% + IVA 22%, notaio in verifica.",
      ch: "Canton Zurigo, atto pubblico e registro fondiario per intero a chi compra; provvigione in verifica.",
      de: "Baviera, Grunderwerbsteuer; notaio, Grundbuch e provvigione in verifica.",
      at: "Grunderwerbsteuer e iscrizione nel Grundbuch; contratto, fiduciario e provvigione in verifica.",
    },
    tabNota: "Le voci «in verifica» non hanno ancora una fonte ufficiale riletta da noi: non entrano nei totali, che quindi si leggono come «almeno».",
  },
  en: {
    titolo: "Purchase costs on Lake Orta: Italy, Switzerland, Germany, Austria",
    descrizione: "Calculator of a buyer's costs on Lake Orta: registration, mortgage and cadastral taxes, VAT, commission, compared with the canton of Zurich, Bavaria and Austria. With sources and dates.",
    h1: "What buying costs, on top of the price.",
    lead: "The same home, the same price, four countries. Taxes, notary and registers, agency: the items the buyer pays, each with its source. In Italy, buying from a private seller, the taxes can be calculated on the cadastral value instead of the price.",
    prezzo: "Price of the home", scala: "Price, on a logarithmic scale", esempi: "Example prices", ipotesi: "Your assumptions, in Italy",
    venditore: "Who is selling", venditori: { privato: "a private seller", impresa: "a company, with VAT" },
    casa: "The home will be", case: { seconda: "second home", prima: "main home" },
    primaAiuto: `For the main-home relief, a buyer not resident in the municipality must move their residence there within ${IT.mesiResidenza} months, declaring it in the deed.`,
    lusso: "Cadastral category A/1, A/8 or A/9", lussoAiuto: "Luxury homes, villas and castles do not get the main-home relief; bought from a company they pay 22% VAT.",
    base: "Tax base", basi: { catastale: "cadastral value (prezzo-valore)", prezzo: "declared price" },
    baseAiuto: "The prezzo-valore rule applies between private individuals, for homes and their annexes, and is requested from the notary in the deed. The real price must still be stated.",
    rendita: "Cadastral income (rendita catastale)", renditaEsempio: "This is an example figure, not data: enter the one in the cadastral record (visura).", renditaAiuto: "You find it in the home's cadastral record (visura catastale).",
    agenzia: "With an agency", agenziaAiuto: "In the province of Novara the custom recorded by the Chamber of Commerce is 3% from each party, plus 22% VAT. It is a 2005 custom, not a legal cap: the signed agreement is what counts.",
    pct: "Buyer's commission", pctTesto: (p, i) => `${p} + VAT ${i}`,
    paesi: { it: "Italy · Lake Orta", ch: "Switzerland · canton of Zurich", de: "Germany · Bavaria", at: "Austria" },
    paesiBreve: { it: "Italy", ch: "Switzerland", de: "Germany", at: "Austria" },
    delPrezzo: (p) => `${p} of the price`, piuInVerifica: "plus, being checked:", soloVerifica: "being checked",
    gruppi: { imposte: "Taxes", registri: "Notary and registers", agenzia: "Agency", verifica: "Being checked" },
    dettaglioCaption: (paese, prezzo) => `Buyer's costs, ${paese}, for a home at ${prezzo}`, totaleRiga: "Total for the buyer",
    nessuna: "none", mancaRendita: "needs the cadastral income",
    chf: "In Switzerland fees and minimums are in francs: we apply them to the same figure, without conversion. The comparison holds as a percentage of the price.",
    ivaNota: "From a company we add VAT on top of the price: check whether the asking price is \"plus VAT\" or \"VAT included\".",
    voci: {
      registro: { nome: (p) => `Registration tax, ${pc(p.aliq, "en")}`, spieg: () => "On the cadastral value: enter the cadastral income to calculate it.", breve: "registration tax", chi: "buyer" },
      registroCatastale: { nome: (p) => `Registration tax, ${pc(p.aliq, "en")}`, spieg: (p) => `On the cadastral value of ${fmtEuro(p.vc, "en")} (income × 1.05 × multiplier), minimum ${fmtEuro(p.min, "en")}.`, breve: "registration tax", chi: "buyer" },
      registroPrezzo: { nome: (p) => `Registration tax, ${pc(p.aliq, "en")}`, spieg: (p) => `On the declared price, minimum ${fmtEuro(p.min, "en")}.`, breve: "registration tax", chi: "buyer" },
      ipocatastali: { nome: () => "Mortgage and cadastral taxes", spieg: (p) => `${fmtEuro(p.ip, "en")} + ${fmtEuro(p.cat, "en")}, fixed, on a sale by a private seller.`, breve: "mortgage and cadastral taxes", chi: "buyer" },
      iva: { nome: (p) => `VAT, ${pc(p.aliq, "en")}`, spieg: () => "On a sale by a company: 4% main home, 10% other homes, 22% for A/1, A/8, A/9.", breve: "VAT", chi: "buyer" },
      fisse: { nome: () => "Registration, mortgage and cadastral taxes", spieg: (p) => `${fmtEuro(p.una, "en")} each, fixed, on a sale with VAT.`, breve: "fixed taxes", chi: "buyer" },
      notaio: { nome: () => "Notary", spieg: () => "There is no tariff: since 2012 the fee is agreed, with a written quote. By custom the buyer chooses and pays the notary.", breve: "notary", chi: "buyer" },
      agenzia: { nome: (p) => `Commission, ${pc(p.pct, "en")} + VAT ${pc(p.iva, "en")}`, spieg: () => "Custom of the province of Novara: 3% from each party, unless agreed otherwise.", breve: "commission", chi: "buyer" },
      chHand: { nome: () => "Transfer tax (Handänderungssteuer)", spieg: () => "The canton of Zurich does not levy it: it is one of six cantons without.", breve: "transfer tax", chi: "—" },
      chBeurk: { nome: (p) => `Public deed (Beurkundung), ${fmtNum(p.pm, "en")}‰`, spieg: (p) => `Of market value, minimum CHF ${fmtNum(p.min, "en")}. Often split between the parties by contract.`, breve: "public deed", chi: "by contract" },
      chGrundbuch: { nome: (p) => `Land register (Grundbuch), ${fmtNum(p.pm, "en")}‰`, spieg: (p) => `Of market value, minimum CHF ${fmtNum(p.min, "en")}, plus Swiss VAT on part of it (not added).`, breve: "land register", chi: "by contract" },
      makler: { nome: () => "Commission", spieg: () => "We found no official source on how much of it the buyer pays: being checked.", breve: "commission", chi: "—" },
      deGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "en")}`, spieg: () => "Property acquisition tax: Bavaria applies the federal rate, the lowest in Germany.", breve: "Grunderwerbsteuer", chi: "buyer" },
      deNotar: { nome: () => "Notary and Grundbuch", spieg: () => "Statutory sliding tariff (GNotKG): not yet re-read by us, so not added.", breve: "notary and Grundbuch", chi: "buyer" },
      atGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "en")}`, spieg: () => "Property acquisition tax, on the price.", breve: "Grunderwerbsteuer", chi: "buyer" },
      atEintragung: { nome: (p) => `Grundbuch registration, ${pc(p.aliq, "en")}`, spieg: (p) => `Of the value, plus a ${fmtEuro(p.eingabe, "en")} filing fee.`, breve: "Grundbuch", chi: "buyer" },
      atNotar: { nome: () => "Contract, notary or lawyer, escrow", spieg: () => "No tariff re-read: being checked.", breve: "contract and escrow", chi: "buyer" },
    },
    annuncio: (r) => r.join("; "),
    metodo: (l) => [
      `Italy, from a private seller: registration tax ${pc(IT.registro, l)}, or ${pc(IT.registroPrima, l)} for a main home, with a minimum of ${fmtEuro(IT.registroMin, l)}; fixed mortgage and cadastral taxes, ${fmtEuro(IT.ipotecaria, l)} + ${fmtEuro(IT.catastale, l)}. Under the prezzo-valore rule the base is the cadastral value: income × ${fmtNum(1 + IT.rivalutazione / 100, l, 2)} × ${IT.moltiplicatore}, or × ${IT.moltiplicatorePrima} for a main home. Without the income the item stays out of the total.`,
      `Italy, from a company: VAT ${pc(IT.ivaPrima, l)} on a main home, ${pc(IT.ivaAltre, l)} on other homes, ${pc(IT.ivaLusso, l)} on A/1, A/8 and A/9; fixed registration, mortgage and cadastral taxes of ${fmtEuro(IT.fisseImpresa, l)} each. Commission follows the Novara custom, ${pc(IT.agenzia.pct, l)} from each party plus ${pc(IT.agenzia.iva, l)} VAT; the notary has no tariff and stays "being checked".`,
      `Switzerland, canton of Zurich: no transfer tax; public deed and land register ${fmtNum(ESTERO.ch.beurkundungPm, l)}‰ each of the value, minimum CHF ${ESTERO.ch.minimo}. Germany, Bavaria: Grunderwerbsteuer ${pc(ESTERO.de.grest, l)}; notary and Grundbuch being checked. Austria: Grunderwerbsteuer ${pc(ESTERO.at.grest, l)}, Grundbuch registration ${pc(ESTERO.at.eintragung, l)} plus ${fmtEuro(ESTERO.at.eingabe, l)}; contract and escrow being checked.`,
      "Outside Italy we do not add commission: we found no official source stating how much of it the buyer pays. That is why the \"With an agency\" switch changes only the Italian row.",
      "When an item moves from \"being checked\" to verified, the calculator adds it by itself: the rule lives in a data file with source and date, not in the code. Totals with missing items read as \"at least\".",
    ],
    guidaLink: "The guide to purchase costs compared",
    tabTitolo: "Three prices, four countries", tabCaption: "Costs of buying a home from a private seller, at three example prices", tabPrezzo: "Price", tabIpotesi: "The table's assumptions",
    ipotesiPaese: {
      it: "Second home from a private seller under prezzo-valore with an example cadastral income of €2,000, commission 3% + 22% VAT, notary being checked.",
      ch: "Canton of Zurich, public deed and land register paid in full by the buyer; commission being checked.",
      de: "Bavaria, Grunderwerbsteuer; notary, Grundbuch and commission being checked.",
      at: "Grunderwerbsteuer and Grundbuch registration; contract, escrow and commission being checked.",
    },
    tabNota: "Items \"being checked\" do not yet have an official source re-read by us: they are left out of the totals, which therefore read as \"at least\".",
  },
  de: {
    titolo: "Kaufnebenkosten am Ortasee: Italien, Schweiz, Deutschland, Österreich",
    descrizione: "Rechner der Kaufnebenkosten am Ortasee: Registersteuer, Hypotheken- und Katastersteuer, Mehrwertsteuer, Provision, verglichen mit dem Kanton Zürich, Bayern und Österreich. Mit Quellen und Datum.",
    h1: "Was der Kauf über den Preis hinaus kostet.",
    lead: "Dasselbe Haus, derselbe Preis, vier Länder. Steuern, Notar und Register, Makler: die Posten, die der Käufer zahlt, jeder mit seiner Quelle. In Italien lassen sich die Steuern beim Kauf von privat auf den Katasterwert statt auf den Preis berechnen.",
    prezzo: "Kaufpreis", scala: "Preis, logarithmische Skala", esempi: "Beispielpreise", ipotesi: "Ihre Annahmen in Italien",
    venditore: "Wer verkauft", venditori: { privato: "eine Privatperson", impresa: "ein Unternehmen, mit MwSt." },
    casa: "Das Haus wird", case: { seconda: "Zweitwohnsitz", prima: "Hauptwohnsitz (prima casa)" },
    primaAiuto: `Für die Erstwohnsitz-Begünstigung muss, wer nicht in der Gemeinde wohnt, den Wohnsitz binnen ${IT.mesiResidenza} Monaten dorthin verlegen und das in der Urkunde erklären.`,
    lusso: "Katasterkategorie A/1, A/8 oder A/9", lussoAiuto: "Herrschaftliche Wohnungen, Villen und Schlösser erhalten keine Erstwohnsitz-Begünstigung; vom Unternehmen zahlen sie 22 % MwSt.",
    base: "Steuerbasis", basi: { catastale: "Katasterwert (prezzo-valore)", prezzo: "erklärter Preis" },
    baseAiuto: "Prezzo-valore gilt zwischen Privatpersonen für Wohnungen und Zubehör und wird beim Notar in der Urkunde beantragt. Der echte Preis muss trotzdem genannt werden.",
    rendita: "Katasterertrag (rendita catastale)", renditaEsempio: "Das ist ein Beispielwert, keine Angabe: Tragen Sie den Wert aus dem Katasterauszug (visura) ein.", renditaAiuto: "Sie finden ihn im Katasterauszug (visura catastale) des Hauses.",
    agenzia: "Mit Makler", agenziaAiuto: "In der Provinz Novara ist der von der Handelskammer erfasste Brauch 3 % je Partei plus 22 % MwSt. Es ist ein Brauch von 2005, keine gesetzliche Obergrenze: Es zählt die unterschriebene Vereinbarung.",
    pct: "Käuferprovision", pctTesto: (p, i) => `${p} + MwSt. ${i}`,
    paesi: { it: "Italien · Ortasee", ch: "Schweiz · Kanton Zürich", de: "Deutschland · Bayern", at: "Österreich" },
    paesiBreve: { it: "Italien", ch: "Schweiz", de: "Deutschland", at: "Österreich" },
    delPrezzo: (p) => `${p} des Preises`, piuInVerifica: "dazu, in Prüfung:", soloVerifica: "in Prüfung",
    gruppi: { imposte: "Steuern", registri: "Notar und Register", agenzia: "Makler", verifica: "In Prüfung" },
    dettaglioCaption: (paese, prezzo) => `Kosten des Käufers, ${paese}, für ein Haus zu ${prezzo}`, totaleRiga: "Summe für den Käufer",
    nessuna: "keine", mancaRendita: "Katasterertrag fehlt",
    chf: "In der Schweiz sind Gebühren und Mindestbeträge in Franken: Wir wenden sie auf denselben Betrag an, ohne Umrechnung. Der Vergleich gilt in Prozent des Preises.",
    ivaNota: "Vom Unternehmen rechnen wir die MwSt. zusätzlich zum Preis: Prüfen Sie, ob der Preis „zzgl. MwSt.“ oder „inkl. MwSt.“ ist.",
    voci: {
      registro: { nome: (p) => `Registersteuer, ${pc(p.aliq, "de")}`, spieg: () => "Auf den Katasterwert: Tragen Sie den Katasterertrag ein.", breve: "Registersteuer", chi: "Käufer" },
      registroCatastale: { nome: (p) => `Registersteuer, ${pc(p.aliq, "de")}`, spieg: (p) => `Auf den Katasterwert von ${fmtEuro(p.vc, "de")} (Ertrag × 1,05 × Multiplikator), mindestens ${fmtEuro(p.min, "de")}.`, breve: "Registersteuer", chi: "Käufer" },
      registroPrezzo: { nome: (p) => `Registersteuer, ${pc(p.aliq, "de")}`, spieg: (p) => `Auf den erklärten Preis, mindestens ${fmtEuro(p.min, "de")}.`, breve: "Registersteuer", chi: "Käufer" },
      ipocatastali: { nome: () => "Hypotheken- und Katastersteuer", spieg: (p) => `${fmtEuro(p.ip, "de")} + ${fmtEuro(p.cat, "de")}, fest, beim Kauf von privat.`, breve: "Hypotheken- und Katastersteuer", chi: "Käufer" },
      iva: { nome: (p) => `MwSt., ${pc(p.aliq, "de")}`, spieg: () => "Beim Kauf vom Unternehmen: 4 % Hauptwohnsitz, 10 % andere Wohnungen, 22 % für A/1, A/8, A/9.", breve: "MwSt.", chi: "Käufer" },
      fisse: { nome: () => "Register-, Hypotheken- und Katastersteuer", spieg: (p) => `Je ${fmtEuro(p.una, "de")}, fest, beim Kauf mit MwSt.`, breve: "feste Steuern", chi: "Käufer" },
      notaio: { nome: () => "Notar", spieg: () => "Es gibt keinen Tarif: Seit 2012 wird das Honorar vereinbart, mit Kostenvoranschlag. Üblicherweise wählt und zahlt ihn der Käufer.", breve: "Notar", chi: "Käufer" },
      agenzia: { nome: (p) => `Provision, ${pc(p.pct, "de")} + MwSt. ${pc(p.iva, "de")}`, spieg: () => "Brauch der Provinz Novara: 3 % je Partei, sofern nichts anderes vereinbart.", breve: "Provision", chi: "Käufer" },
      chHand: { nome: () => "Handänderungssteuer", spieg: () => "Der Kanton Zürich erhebt sie nicht: einer von sechs Kantonen ohne.", breve: "Handänderungssteuer", chi: "—" },
      chBeurk: { nome: (p) => `Beurkundung, ${fmtNum(p.pm, "de")} ‰`, spieg: (p) => `Vom Verkehrswert, mindestens CHF ${fmtNum(p.min, "de")}. Oft vertraglich geteilt.`, breve: "Beurkundung", chi: "laut Vertrag" },
      chGrundbuch: { nome: (p) => `Grundbuch, ${fmtNum(p.pm, "de")} ‰`, spieg: (p) => `Vom Verkehrswert, mindestens CHF ${fmtNum(p.min, "de")}, dazu teils MwSt. (nicht addiert).`, breve: "Grundbuch", chi: "laut Vertrag" },
      makler: { nome: () => "Provision", spieg: () => "Keine amtliche Quelle gefunden, wie viel davon der Käufer zahlt: in Prüfung.", breve: "Provision", chi: "—" },
      deGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "de")}`, spieg: () => "Bayern wendet den Bundessatz an, den niedrigsten in Deutschland.", breve: "Grunderwerbsteuer", chi: "Käufer" },
      deNotar: { nome: () => "Notar und Grundbuch", spieg: () => "Degressiver Gesetzestarif (GNotKG): von uns noch nicht nachgelesen, daher nicht addiert.", breve: "Notar und Grundbuch", chi: "Käufer" },
      atGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "de")}`, spieg: () => "Auf den Kaufpreis.", breve: "Grunderwerbsteuer", chi: "Käufer" },
      atEintragung: { nome: (p) => `Grundbucheintragung, ${pc(p.aliq, "de")}`, spieg: (p) => `Vom Wert, dazu ${fmtEuro(p.eingabe, "de")} Eingabegebühr.`, breve: "Grundbuch", chi: "Käufer" },
      atNotar: { nome: () => "Vertrag, Notar oder Anwalt, Treuhand", spieg: () => "Kein Tarif nachgelesen: in Prüfung.", breve: "Vertrag und Treuhand", chi: "Käufer" },
    },
    annuncio: (r) => r.join("; "),
    metodo: (l) => [
      `Italien, Kauf von privat: Registersteuer ${pc(IT.registro, l)}, oder ${pc(IT.registroPrima, l)} beim Hauptwohnsitz, mindestens ${fmtEuro(IT.registroMin, l)}; feste Hypotheken- und Katastersteuer, ${fmtEuro(IT.ipotecaria, l)} + ${fmtEuro(IT.catastale, l)}. Mit prezzo-valore ist die Basis der Katasterwert: Ertrag × ${fmtNum(1 + IT.rivalutazione / 100, l, 2)} × ${IT.moltiplicatore}, oder × ${IT.moltiplicatorePrima} beim Hauptwohnsitz. Ohne Ertrag bleibt der Posten außerhalb der Summe.`,
      `Italien, Kauf vom Unternehmen: MwSt. ${pc(IT.ivaPrima, l)} beim Hauptwohnsitz, ${pc(IT.ivaAltre, l)} bei anderen Wohnungen, ${pc(IT.ivaLusso, l)} bei A/1, A/8 und A/9; feste Register-, Hypotheken- und Katastersteuer von je ${fmtEuro(IT.fisseImpresa, l)}. Die Provision folgt dem Brauch der Provinz Novara, ${pc(IT.agenzia.pct, l)} je Partei plus ${pc(IT.agenzia.iva, l)} MwSt.; der Notar hat keinen Tarif und bleibt „in Prüfung“.`,
      `Schweiz, Kanton Zürich: keine Handänderungssteuer; Beurkundung und Grundbuch je ${fmtNum(ESTERO.ch.beurkundungPm, l)} ‰ des Werts, mindestens CHF ${ESTERO.ch.minimo}. Deutschland, Bayern: Grunderwerbsteuer ${pc(ESTERO.de.grest, l)}; Notar und Grundbuch in Prüfung. Österreich: Grunderwerbsteuer ${pc(ESTERO.at.grest, l)}, Grundbucheintragung ${pc(ESTERO.at.eintragung, l)} plus ${fmtEuro(ESTERO.at.eingabe, l)}; Vertrag und Treuhand in Prüfung.`,
      "Außerhalb Italiens addieren wir keine Provision: Wir haben keine amtliche Quelle gefunden, die sagt, wie viel davon der Käufer zahlt. Deshalb ändert der Schalter „Mit Makler“ nur die italienische Zeile.",
      "Wird ein Posten von „in Prüfung“ zu geprüft, addiert ihn der Rechner von selbst: Die Regel steht in einer Datendatei mit Quelle und Datum, nicht im Code. Summen mit fehlenden Posten lesen sich als „mindestens“.",
    ],
    guidaLink: "Der Ratgeber zu den Kaufnebenkosten im Vergleich",
    tabTitolo: "Drei Preise, vier Länder", tabCaption: "Kosten des Käufers beim Kauf von privat, zu drei Beispielpreisen", tabPrezzo: "Preis", tabIpotesi: "Die Annahmen der Tabelle",
    ipotesiPaese: {
      it: "Zweitwohnsitz von privat mit prezzo-valore und einem Beispiel-Katasterertrag von 2.000 €, Provision 3 % + 22 % MwSt., Notar in Prüfung.",
      ch: "Kanton Zürich, Beurkundung und Grundbuch ganz beim Käufer; Provision in Prüfung.",
      de: "Bayern, Grunderwerbsteuer; Notar, Grundbuch und Provision in Prüfung.",
      at: "Grunderwerbsteuer und Grundbucheintragung; Vertrag, Treuhand und Provision in Prüfung.",
    },
    tabNota: "Posten „in Prüfung“ haben noch keine von uns nachgelesene amtliche Quelle: Sie fehlen in den Summen, die sich daher als „mindestens“ lesen.",
  },
  sl: {
    titolo: "Stroški nakupa ob jezeru Orta: Italija, Švica, Nemčija, Avstrija",
    descrizione: "Kalkulator stroškov kupca ob jezeru Orta: davek na registracijo, hipotekarni in katastrski davek, DDV, provizija, v primerjavi s kantonom Zürich, Bavarsko in Avstrijo. Z viri in datumi.",
    h1: "Koliko stane nakup poleg cene.",
    lead: "Ista hiša, ista cena, štiri države. Davki, notar in registri, agencija: postavke, ki jih plača kupec, vsaka s svojim virom. V Italiji se lahko davki pri nakupu od zasebnika izračunajo na katastrsko vrednost namesto na ceno.",
    prezzo: "Cena hiše", scala: "Cena, na logaritemski lestvici", esempi: "Primeri cen", ipotesi: "Vaše predpostavke v Italiji",
    venditore: "Kdo prodaja", venditori: { privato: "zasebnik", impresa: "podjetje, z DDV" },
    casa: "Hiša bo", case: { seconda: "druga nepremičnina", prima: "prvo bivališče (prima casa)" },
    primaAiuto: `Za olajšavo za prvo bivališče mora kupec, ki ne prebiva v občini, tja prenesti stalno prebivališče v ${IT.mesiResidenza} mesecih in to izjaviti v pogodbi.`,
    lusso: "Katastrska kategorija (categoria catastale) A/1, A/8 ali A/9", lussoAiuto: "Razkošna stanovanja, vile in gradovi nimajo olajšave za prvo bivališče; od podjetja plačajo 22 % DDV.",
    base: "Osnova za davke", basi: { catastale: "katastrska vrednost (prezzo-valore)", prezzo: "navedena cena" },
    baseAiuto: "Pravilo prezzo-valore velja med fizičnimi osebami za stanovanja in pripadajoče prostore; zahteva se pri notarju v pogodbi. Pravo ceno je treba vseeno navesti.",
    rendita: "Katastrski donos (rendita catastale)", renditaEsempio: "To je primer, ne podatek: vpišite znesek iz katastrskega izpiska (visura).", renditaAiuto: "Najdete ga v katastrskem izpisku (visura catastale) hiše.",
    agenzia: "Z agencijo", agenziaAiuto: "V pokrajini Novara je običaj, ki ga je zbrala gospodarska zbornica, 3 % za vsako stranko, plus 22 % DDV. Gre za običaj iz leta 2005, ne za zakonsko zgornjo mejo: šteje podpisani dogovor.",
    pct: "Provizija kupca", pctTesto: (p, i) => `${p} + DDV ${i}`,
    paesi: { it: "Italija · jezero Orta", ch: "Švica · kanton Zürich", de: "Nemčija · Bavarska", at: "Avstrija" },
    paesiBreve: { it: "Italija", ch: "Švica", de: "Nemčija", at: "Avstrija" },
    delPrezzo: (p) => `${p} cene`, piuInVerifica: "in še, v preverjanju:", soloVerifica: "v preverjanju",
    gruppi: { imposte: "Davki", registri: "Notar in registri", agenzia: "Agencija", verifica: "V preverjanju" },
    dettaglioCaption: (paese, prezzo) => `Stroški kupca, ${paese}, za hišo po ceni ${prezzo}`, totaleRiga: "Skupaj za kupca",
    nessuna: "ni", mancaRendita: "manjka katastrski donos",
    chf: "V Švici so pristojbine in najnižji zneski v frankih: uporabimo jih na istem znesku, brez preračuna. Primerjava velja v odstotku cene.",
    ivaNota: "Pri nakupu od podjetja DDV prištejemo ceni: preverite, ali je cena »plus DDV« ali »z DDV«.",
    voci: {
      registro: { nome: (p) => `Davek na registracijo (imposta di registro), ${pc(p.aliq, "sl")}`, spieg: () => "Na katastrsko vrednost: vpišite katastrski donos.", breve: "davek na registracijo", chi: "kupec" },
      registroCatastale: { nome: (p) => `Davek na registracijo (imposta di registro), ${pc(p.aliq, "sl")}`, spieg: (p) => `Na katastrsko vrednost ${fmtEuro(p.vc, "sl")} (donos × 1,05 × količnik), najmanj ${fmtEuro(p.min, "sl")}.`, breve: "davek na registracijo", chi: "kupec" },
      registroPrezzo: { nome: (p) => `Davek na registracijo (imposta di registro), ${pc(p.aliq, "sl")}`, spieg: (p) => `Na navedeno ceno, najmanj ${fmtEuro(p.min, "sl")}.`, breve: "davek na registracijo", chi: "kupec" },
      ipocatastali: { nome: () => "Hipotekarni in katastrski davek", spieg: (p) => `${fmtEuro(p.ip, "sl")} + ${fmtEuro(p.cat, "sl")}, fiksno, pri nakupu od zasebnika.`, breve: "hipotekarni in katastrski davek", chi: "kupec" },
      iva: { nome: (p) => `DDV, ${pc(p.aliq, "sl")}`, spieg: () => "Pri nakupu od podjetja: 4 % prvo bivališče, 10 % druga stanovanja, 22 % za A/1, A/8, A/9.", breve: "DDV", chi: "kupec" },
      fisse: { nome: () => "Davek na registracijo, hipotekarni in katastrski davek", spieg: (p) => `Vsak po ${fmtEuro(p.una, "sl")}, fiksno, pri nakupu z DDV.`, breve: "fiksni davki", chi: "kupec" },
      notaio: { nome: () => "Notar", spieg: () => "Tarife ni: od leta 2012 se honorar dogovori, s predračunom. Po običaju notarja izbere in plača kupec.", breve: "notar", chi: "kupec" },
      agenzia: { nome: (p) => `Provizija, ${pc(p.pct, "sl")} + DDV ${pc(p.iva, "sl")}`, spieg: () => "Običaj pokrajine Novara: 3 % za vsako stranko, če ni dogovorjeno drugače.", breve: "provizija", chi: "kupec" },
      chHand: { nome: () => "Davek na prenos (Handänderungssteuer)", spieg: () => "Kanton Zürich ga ne pobira: je eden od šestih kantonov brez njega.", breve: "davek na prenos", chi: "—" },
      chBeurk: { nome: (p) => `Javna listina (Beurkundung), ${fmtNum(p.pm, "sl")} ‰`, spieg: (p) => `Od tržne vrednosti, najmanj ${fmtNum(p.min, "sl")} CHF. Pogosto si jo stranki razdelita po pogodbi.`, breve: "javna listina", chi: "po pogodbi" },
      chGrundbuch: { nome: (p) => `Zemljiška knjiga (Grundbuch), ${fmtNum(p.pm, "sl")} ‰`, spieg: (p) => `Od tržne vrednosti, najmanj ${fmtNum(p.min, "sl")} CHF, delno še švicarski DDV (ni prištet).`, breve: "zemljiška knjiga", chi: "po pogodbi" },
      makler: { nome: () => "Provizija", spieg: () => "Uradnega vira o tem, koliko je plača kupec, nismo našli: v preverjanju.", breve: "provizija", chi: "—" },
      deGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "sl")}`, spieg: () => "Davek na pridobitev: Bavarska uporablja zvezno stopnjo, najnižjo v Nemčiji.", breve: "Grunderwerbsteuer", chi: "kupec" },
      deNotar: { nome: () => "Notar in Grundbuch", spieg: () => "Padajoča zakonska tarifa (GNotKG): še je nismo preverili, zato je ne prištejemo.", breve: "notar in Grundbuch", chi: "kupec" },
      atGrest: { nome: (p) => `Grunderwerbsteuer, ${pc(p.aliq, "sl")}`, spieg: () => "Davek na pridobitev, na ceno.", breve: "Grunderwerbsteuer", chi: "kupec" },
      atEintragung: { nome: (p) => `Vpis v Grundbuch, ${pc(p.aliq, "sl")}`, spieg: (p) => `Od vrednosti, plus ${fmtEuro(p.eingabe, "sl")} vložne pristojbine.`, breve: "Grundbuch", chi: "kupec" },
      atNotar: { nome: () => "Pogodba, notar ali odvetnik, fiduciar", spieg: () => "Tarife nismo preverili: v preverjanju.", breve: "pogodba in fiduciar", chi: "kupec" },
    },
    annuncio: (r) => r.join("; "),
    metodo: (l) => [
      `Italija, nakup od zasebnika: davek na registracijo ${pc(IT.registro, l)}, ali ${pc(IT.registroPrima, l)} za prvo bivališče, najmanj ${fmtEuro(IT.registroMin, l)}; fiksni hipotekarni in katastrski davek, ${fmtEuro(IT.ipotecaria, l)} + ${fmtEuro(IT.catastale, l)}. Po pravilu prezzo-valore je osnova katastrska vrednost: donos × ${fmtNum(1 + IT.rivalutazione / 100, l, 2)} × ${IT.moltiplicatore}, ali × ${IT.moltiplicatorePrima} za prvo bivališče. Brez donosa postavka ostane zunaj seštevka.`,
      `Italija, nakup od podjetja: DDV ${pc(IT.ivaPrima, l)} za prvo bivališče, ${pc(IT.ivaAltre, l)} za druga stanovanja, ${pc(IT.ivaLusso, l)} za A/1, A/8 in A/9; fiksni davki po ${fmtEuro(IT.fisseImpresa, l)}. Provizija sledi običaju pokrajine Novara, ${pc(IT.agenzia.pct, l)} za vsako stranko plus ${pc(IT.agenzia.iva, l)} DDV; notar nima tarife in ostane »v preverjanju«.`,
      `Švica, kanton Zürich: brez davka na prenos; javna listina in zemljiška knjiga po ${fmtNum(ESTERO.ch.beurkundungPm, l)} ‰ vrednosti, najmanj ${ESTERO.ch.minimo} CHF. Nemčija, Bavarska: Grunderwerbsteuer ${pc(ESTERO.de.grest, l)}; notar in Grundbuch v preverjanju. Avstrija: Grunderwerbsteuer ${pc(ESTERO.at.grest, l)}, vpis v Grundbuch ${pc(ESTERO.at.eintragung, l)} plus ${fmtEuro(ESTERO.at.eingabe, l)}; pogodba in fiduciar v preverjanju.`,
      "Zunaj Italije provizije ne prištejemo: nismo našli uradnega vira, ki bi povedal, koliko je plača kupec. Zato stikalo »Z agencijo« spremeni le italijansko vrstico.",
      "Ko postavka preide iz »v preverjanju« med preverjene, jo kalkulator prišteje sam: pravilo je v podatkovni datoteki z virom in datumom, ne v kodi. Seštevke z manjkajočimi postavkami beremo kot »najmanj«.",
    ],
    guidaLink: "Vodnik o stroških nakupa v primerjavi",
    tabTitolo: "Tri cene, štiri države", tabCaption: "Stroški kupca pri nakupu od zasebnika, pri treh primerih cene", tabPrezzo: "Cena", tabIpotesi: "Predpostavke tabele",
    ipotesiPaese: {
      it: "Druga nepremičnina od zasebnika po pravilu prezzo-valore, s primerom katastrskega donosa 2.000 €, provizija 3 % + 22 % DDV, notar v preverjanju.",
      ch: "Kanton Zürich, javna listina in zemljiška knjiga v celoti na kupcu; provizija v preverjanju.",
      de: "Bavarska, Grunderwerbsteuer; notar, Grundbuch in provizija v preverjanju.",
      at: "Grunderwerbsteuer in vpis v Grundbuch; pogodba, fiduciar in provizija v preverjanju.",
    },
    tabNota: "Postavke »v preverjanju« še nimajo uradnega vira, ki bi ga preverili: niso v seštevkih, zato jih beremo kot »najmanj«.",
  },
};
