import type { Lingua } from "@/lib/rotte";

// I testi della home. Ogni numero viene dai dati (src/data, 6 ottobre 2026) o dal CRM del
// gruppo (conteggi del 5 ottobre 2026); qui stanno le frasi, i numeri entrano come argomenti.
export type TestiHome = {
  titolo: string; descrizione: string;
  coordinate: string; h1: string; nastroDa: string; nastroNota: string; ctaPC: string; ctaCarta: string; statoLungo: string;
  rilievoAlt: string;
  voloAria: string; voloEtichetta: string;
  cap: {
    h2: string; corpo: string; scheda: [string, string][]; lente?: { src: string; alt: string; credito: string };
  }[];
  mondiTitolo: string; luoghiTitolo: string; mondiNota: string; esplora: string;
  daCasa: { occhiello: string; h2: string; lead: string; tuttiTempi: string; tabellaTitolo: string; colonne: [string, string, string, string]; nota: string; tutteDistanze: string; rispetto: string; riferimento: string };
  metodo: { occhiello: string; h2: string; lead: string; caso: string; passi: { titolo: string; testo: string }[]; tour: string; tourSotto: string; film: string; filmSotto: string; pc: string };
  chiCompra: { h3: string; colA: string; colB: string; numA: string; cosaA: string; numB: string; cosaB: string; altriA: [string, string][]; altriB: [string, string][]; altri: string; nota: string; chiusa: string; proprietari: string };
  collezione: { occhiello: string; h2: string; zero: string; trieste: string; triesteLink: string; invito: string };
  gruppo: { occhiello: string; h2: string; lead: string; numeri: [string, string][]; marchi: { nome: string; dove: string; href: string }[]; canale: string; canaleNum: string; canaleSotto: string; canaleLink: string; nota: string };
  epilogo: { occhiello: string; h2: string; guide: string; video: string };
};

const it: TestiHome = {
  titolo: "OrtaVillas · Il lago d'Orta, misurato da Milano",
  descrizione: "Il lago d'Orta fra 67 e 96 minuti da piazza del Duomo: tempi OSRM, quote, sole d'inverno, quotazioni OMI e il metodo di TriesteVillas. Edizione 01, ottobre 2026.",
  coordinate: "Origine dei tempi · 45.464° N · 9.191° E",
  h1: "Settantacinque minuti da Milano comincia un altro lago.",
  nastroDa: "Piazza del Duomo",
  nastroNota: "senza traffico, OSRM",
  ctaPC: "Private Collection: avvisatemi per primi",
  ctaCarta: "Aprite la carta",
  statoLungo: "Ottobre 2026 · Sul lago d'Orta possiamo già mediare: TriesteVillas è un'agenzia iscritta in Italia. Ma oggi in collezione non c'è nessuna casa del lago, e lo diciamo: prima l'atlante, poi le case.",
  rilievoAlt: "Rilievo ombreggiato del lago d'Orta e delle montagne intorno, dal Mottarone alla Valle Strona, con i sedici luoghi dell'atlante e i minuti da Milano.",
  voloAria: "Il volo: dall'autostrada al lago, in cinque inquadrature",
  voloEtichetta: "Il volo",
  cap: [
    {
      h2: "L'uscita giusta è Borgomanero.",
      corpo: "Da Milano si esce sull'A8 dei Laghi, si prende la diramazione per Gattico e si lascia l'A26 a Borgomanero: da lì la statale 229 sale lungo la riva est. Da Malpensa è più vicino ancora. In treno, invece, Milano non ha un collegamento diretto.",
      scheda: [["Milano Duomo → Orta", "75 min · 87 km"], ["Malpensa T1 → Orta", "54 min · 47 km"], ["Orta-Miasino → Milano in treno", "1 h 33 – 1 h 54, cambio a Novara"]],
    },
    {
      h2: "Orta San Giulio, a 75 minuti da piazza del Duomo.",
      corpo: "Il borgo, piazza Motta, il Palazzotto del 1582 e, a circa 400 metri dalla riva, l'isola di San Giulio con la basilica che nasce da un oratorio della fine del IV secolo. Alle spalle il Sacro Monte, patrimonio UNESCO dal 2003. Qui stanno anche le quotazioni più alte del lago.",
      scheda: [["Orta San Giulio", "75 min · 87 km"], ["Isola di San Giulio", "circa 400 m dalla riva"], ["Ville, lungolago e isola", "2.100–3.000 €/m² · OMI, 2° sem. 2025"]],
      lente: { src: "/assets/images/lago-orta-isola-san-giulio-dallalto.jpg", alt: "L'isola di San Giulio vista dall'alto, con la basilica e il campanile sull'acqua verde del lago.", credito: "Ripresa reale · Unsplash" },
    },
    {
      h2: "Il lago, senza auto.",
      corpo: "Da marzo a ottobre i battelli di linea della Navigazione Lago d'Orta toccano Omegna, Orta, l'isola, Pella, Pettenasco e Gozzano. Sulla riva est corre la ferrovia Novara–Domodossola, con cinque stazioni sul lago. D'inverno il battello di linea si ferma.",
      scheda: [["Battelli di linea", "marzo – ottobre · 3 motonavi"], ["Stazioni sul lago", "Gozzano, Bolzano Novarese, Orta-Miasino, Pettenasco, Omegna"], ["Orta-Miasino → Novara", "8 treni un mercoledì · 42–53 min"]],
      lente: { src: "/assets/images/pontile-tramonto-lago-orta.jpg", alt: "Un pontile di legno sul lago d'Orta al tramonto, con l'acqua ferma e i monti in controluce.", credito: "Ripresa reale · Unsplash" },
    },
    {
      h2: "Duecento metri più su, due ore di sole in più.",
      corpo: "Sopra la riva est, sul versante del Mottarone, Ameno, Vacciago, Miasino e Armeno stanno fra 478 e 543 metri. Il 21 dicembre Ameno e Vacciago sono i luoghi del lago con più sole diretto: la montagna, che a Omegna e sulla sponda ovest nasconde il sole presto, qui sta alle spalle. La funivia da Stresa alla vetta resta chiusa dal 2021.",
      scheda: [["Sole diretto il 21 dicembre", "Ameno 8 h 04 · Omegna 5 h 37"], ["Ultimo sole a Ronco, 21 dicembre", "14:06"], ["Quote", "Armeno 543 m · Ameno 531 m · Miasino 478 m"]],
      lente: { src: "/assets/images/panorama-mottarone-lago-orta.jpg", alt: "Prati del Mottarone con il lago d'Orta in basso e le colline in lontananza.", credito: "Ripresa reale · Unsplash" },
    },
    {
      h2: "Quattro mondi in mezz'ora.",
      corpo: "La sponda est, la sponda ovest, le colline del Mottarone e i due capi del lago. Da un capo all'altro sono dodici chilometri e mezzo d'acqua; ogni luogo ha la sua pagina, con i tempi, la quota, il sole e le quotazioni.",
      scheda: [],
    },
  ],
  mondiTitolo: "I quattro mondi",
  luoghiTitolo: "I sedici luoghi, dal più vicino a Milano",
  mondiNota: "Confini dei mondi indicativi, tracciati da noi.",
  esplora: "Esplorate i luoghi",
  daCasa: {
    occhiello: "Da casa vostra",
    h2: "Da dove partite?",
    lead: "Scegliete la città di partenza: i tempi seguono la strada vera, con la differenza rispetto a Milano. Tre domande, e la carta mette in fila i tre luoghi che vi somigliano.",
    tuttiTempi: "Tutti i tempi: luogo per luogo e la tabella completa",
    tabellaTitolo: "Tempi in auto, luogo per luogo",
    colonne: ["Luogo", "Mondo", "Tempo in auto", "Chilometri"],
    nota: "OSRM senza traffico, misurato il 6 ottobre 2026. Non contano code, cantieri, pedaggi né i controlli al confine svizzero: d'estate e nei fine settimana i tempi reali sono più lunghi.",
    tutteDistanze: "Tutte le distanze",
    rispetto: "rispetto a Milano",
    riferimento: "riferimento",
  },
  metodo: {
    occhiello: "Il metodo",
    h2: "Come una casa arriva a un compratore di Zurigo.",
    lead: "Prima di raccontare una casa la studiamo. Sul lago d'Orta non abbiamo ancora un caso pubblico: qui sotto c'è il metodo di ogni giorno a Trieste, su una casa vera.",
    caso: "Il caso: Villa storica Strada Costiera, su triestevillas.com · TSV-PROP-0003",
    passi: [
      { titolo: "Analisi", testo: "Documenti, catasto, conformità e quotazioni vicine. Prima di scrivere una riga sappiamo che cosa presentiamo, punti deboli compresi." },
      { titolo: "Rilievo", testo: "Fotografie, planimetria e tour 3D: la casa si visita da Zurigo prima che qualcuno si metta in viaggio." },
      { titolo: "Racconto", testo: "Testi in quattro lingue e un film della casa, con i suoi limiti detti." },
      { titolo: "Pubblicazione", testo: "La stessa scheda in italiano, inglese, tedesco e sloveno, con l'uso dell'AI sulle foto dichiarato foto per foto." },
      { titolo: "Private Collection", testo: "Le case che non vanno sui portali arrivano solo a chi si è iscritto, con un accesso personale." },
    ],
    tour: "Aprite il tour 3D", tourSotto: "Matterport · si carica al clic",
    film: "Guardate il film", filmSotto: "YouTube senza cookie · si carica al clic",
    pc: "A Trieste, oggi, 22 case riservate",
  },
  chiCompra: {
    h3: "La domanda c'è già, e scrive da lontano.",
    colA: "Il gruppo · CRM TriesteVillas, ultimi dodici mesi",
    colB: "Il mercato intorno al lago · OMI, compravendite 2025",
    numA: "1.312", cosaA: "compratori ci hanno scritto",
    numB: "4.142", cosaB: "abitazioni compravendute nei comuni della provincia di Novara, capoluogo escluso",
    altriA: [["391", "con un budget da 500.000 € in su"], ["152", "da 1.000.000 € in su"], ["105", "da Austria, Germania e Svizzera"], ["262", "hanno chiesto una villa o una casa indipendente"]],
    altriB: [["+14,0%", "rispetto al 2024, provincia di Novara"], ["2.251", "nei comuni del Verbano-Cusio-Ossola, capoluogo escluso"], ["+10,1%", "rispetto al 2024, Verbano-Cusio-Ossola"], ["+3,2%", "variazione mediana delle quotazioni OMI sul lago in un anno"]],
    altri: "Gli altri quattro numeri",
    nota: "Le richieste del CRM riguardano case a Trieste e dintorni, non sul lago d'Orta; la nazionalità è nota per una parte dei compratori. Conteggi del 5 ottobre 2026, esclusi collaudi, doppioni e spam. Compravendite: Agenzia delle Entrate, OMI, volumi 2025 provvisori (NTN), estratti il 6 ottobre 2026; sono province intere, non il solo lago.",
    chiusa: "Molti di loro il lago d'Orta non l'hanno mai visto. Questo atlante glielo mostra.",
    proprietari: "Avete una casa sul lago? Ecco come la racconteremmo",
  },
  collezione: {
    occhiello: "Private Collection · Lago d'Orta",
    h2: "Le prime case del lago arriveranno qui, prima che altrove.",
    zero: "Oggi in collezione: 0 case del lago. Vi scriviamo quando entra la prima nelle vostre zone.",
    trieste: "A Trieste la nostra Private Collection conta oggi 22 case riservate, 15 delle quali da 1.000.000 € in su.",
    triesteLink: "Com'è la Private Collection a Trieste",
    invito: "Lasciateci un indirizzo e le zone che vi interessano: vi scriviamo quando entra la prima casa, e non prima.",
  },
  gruppo: {
    occhiello: "Il gruppo",
    h2: "Dietro l'atlante, TriesteVillas.",
    lead: "Sei siti dal Tagliamento al Carso, e da oggi il lago d'Orta. Sono i numeri del gruppo, contati nel nostro CRM e sui nostri siti: ognuno ha la sua fonte e la sua data.",
    numeri: [["90", "immobili online sui quattro siti del gruppo"], ["1.312", "compratori ci hanno scritto in dodici mesi"], ["529", "visite fatte in dodici mesi"], ["4,5/5", "su Google, 73 recensioni"]],
    marchi: [
      { nome: "TriesteVillas", dove: "Case di pregio a Trieste", href: "https://triestevillas.com/" },
      { nome: "TriesteImmobiliare", dove: "Le case di ogni giorno", href: "https://triesteimmobiliare.com/" },
      { nome: "TriesteAffitti", dove: "Affitti a Trieste", href: "https://triesteaffitti.com/" },
      { nome: "FriuliVillas", dove: "Ville e case in Friuli", href: "https://friulivillas.com/" },
      { nome: "LignanoVillas", dove: "Case al mare a Lignano", href: "https://lignanovillas.com/" },
      { nome: "SloveniaVillas", dove: "Costa slovena e Carso", href: "https://sloveniavillas.com/" },
    ],
    canale: "Il canale · @TriesteVillasImmobiliare", canaleNum: "1.990.369", canaleSotto: "visualizzazioni · 140 video, dal 2015", canaleLink: "Il canale su YouTube",
    nota: "Fonti: CRM TriesteVillas e cataloghi pubblici dei siti del gruppo, conteggi del 5 ottobre 2026; Google e YouTube alla stessa data.",
  },
  epilogo: {
    occhiello: "Dall'altra parte della collina",
    h2: "Adesso sapete che cosa c'è dietro il Mottarone.",
    guide: "Le guide",
    video: "Ripresa reale · lago d'Orta, da una proprietà sul lago",
  },
};

const en: TestiHome = {
  titolo: "OrtaVillas · Lake Orta, measured from Milan",
  descrizione: "Lake Orta between 67 and 96 minutes from Piazza del Duomo: OSRM drive times, altitudes, winter sunshine, OMI price ranges and the TriesteVillas method. Edition 01, October 2026.",
  coordinate: "Origin of drive times · 45.464° N · 9.191° E",
  h1: "Seventy-five minutes from Milan, another lake begins.",
  nastroDa: "Piazza del Duomo",
  nastroNota: "no traffic, OSRM",
  ctaPC: "Private Collection: tell me first",
  ctaCarta: "Open the map",
  statoLungo: "October 2026 · On Lake Orta we can already act for buyers and sellers: TriesteVillas is an estate agency registered in Italy. But today the collection holds no house on the lake, and we say so: the atlas first, then the houses.",
  rilievoAlt: "Shaded relief of Lake Orta and the mountains around it, from the Mottarone to the Valle Strona, with the atlas's sixteen places and their minutes from Milan.",
  voloAria: "The flight: from the motorway to the lake, in five shots",
  voloEtichetta: "The flight",
  cap: [
    {
      h2: "The exit you want is Borgomanero.",
      corpo: "From Milan you take the A8 Autostrada dei Laghi, follow the branch towards Gattico and leave the A26 at Borgomanero: from there the SS229 climbs along the eastern shore. From Malpensa it is closer still. By train, on the other hand, there is no direct link from Milan.",
      scheda: [["Milan Duomo → Orta", "75 min · 87 km"], ["Malpensa T1 → Orta", "54 min · 47 km"], ["Orta-Miasino → Milan by train", "1 h 33 – 1 h 54, change at Novara"]],
    },
    {
      h2: "Orta San Giulio, 75 minutes from Piazza del Duomo.",
      corpo: "The old village, Piazza Motta, the Palazzotto of 1582 and, some 400 metres offshore, the island of San Giulio, whose basilica grew out of an oratory of the late fourth century. Behind it rises the Sacro Monte, a UNESCO World Heritage Site since 2003. This is also where the lake's highest price ranges are.",
      scheda: [["Orta San Giulio", "75 min · 87 km"], ["Isola di San Giulio", "about 400 m offshore"], ["Villas, lakefront and island", "€2,100–3,000/m² · OMI, H2 2025"]],
      lente: { src: "/assets/images/lago-orta-isola-san-giulio-dallalto.jpg", alt: "The island of San Giulio seen from above, its basilica and bell tower set on the green water of the lake.", credito: "Real photograph · Unsplash" },
    },
    {
      h2: "The lake, without a car.",
      corpo: "From March to October the scheduled boats of Navigazione Lago d'Orta call at Omegna, Orta, the island, Pella, Pettenasco and Gozzano. The Novara–Domodossola railway runs along the eastern shore, with five stations on the lake. In winter the scheduled boats stop.",
      scheda: [["Scheduled boats", "March – October · 3 motor vessels"], ["Stations on the lake", "Gozzano, Bolzano Novarese, Orta-Miasino, Pettenasco, Omegna"], ["Orta-Miasino → Novara", "8 trains on a sample Wednesday · 42–53 min"]],
      lente: { src: "/assets/images/pontile-tramonto-lago-orta.jpg", alt: "A wooden jetty on Lake Orta at sunset, the water still and the mountains backlit.", credito: "Real photograph · Unsplash" },
    },
    {
      h2: "Two hundred metres higher, two more hours of sun.",
      corpo: "Above the eastern shore, on the Mottarone side, Ameno, Vacciago, Miasino and Armeno sit between 478 and 543 metres. On 21 December Ameno and Vacciago get more direct sunlight than anywhere else on the lake: the mountain that hides the sun early at Omegna and on the western shore stands behind them here. The cable car from Stresa to the summit has been closed since 2021.",
      scheda: [["Direct sun on 21 December", "Ameno 8 h 04 · Omegna 5 h 37"], ["Last sun at Ronco, 21 December", "14:06"], ["Altitudes", "Armeno 543 m · Ameno 531 m · Miasino 478 m"]],
      lente: { src: "/assets/images/panorama-mottarone-lago-orta.jpg", alt: "Meadows on the Mottarone, with Lake Orta below and hills in the distance.", credito: "Real photograph · Unsplash" },
    },
    {
      h2: "Four worlds in half an hour.",
      corpo: "The eastern shore, the western shore, the Mottarone hills and the two ends of the lake. From one end to the other is twelve and a half kilometres of water; every place has its own page, with drive times, altitude, sunshine and price ranges.",
      scheda: [],
    },
  ],
  mondiTitolo: "The four worlds",
  luoghiTitolo: "The sixteen places, nearest to Milan first",
  mondiNota: "The boundaries of the worlds are indicative, drawn by us.",
  esplora: "Explore the places",
  daCasa: {
    occhiello: "From your door",
    h2: "Where are you setting off from?",
    lead: "Choose your starting city: the times follow the real roads, with the difference compared with Milan. Three questions, and the map lines up the three places most like you.",
    tuttiTempi: "All drive times: place by place, and the full table",
    tabellaTitolo: "Drive times, place by place",
    colonne: ["Place", "World", "Drive time", "Kilometres"],
    nota: "OSRM without traffic, measured on 6 October 2026. Queues, roadworks, tolls and Swiss border checks are not included: in summer and at weekends real journeys take longer.",
    tutteDistanze: "All distances",
    rispetto: "compared with Milan",
    riferimento: "reference",
  },
  metodo: {
    occhiello: "The method",
    h2: "How a house reaches a buyer in Zurich.",
    lead: "Before we describe a house, we study it. We do not yet have a public case on Lake Orta: below is the method we use every day in Trieste, on a real house.",
    caso: "The case: Villa storica Strada Costiera, on triestevillas.com · TSV-PROP-0003",
    passi: [
      { titolo: "Analysis", testo: "Documents, land registry, compliance and nearby price ranges. Before we write a line we know what we are presenting, weak points included." },
      { titolo: "Survey", testo: "Photographs, floor plan and 3D tour: the house can be visited from Zurich before anyone sets off." },
      { titolo: "Story", testo: "Texts in four languages and a film of the house, with its limits stated." },
      { titolo: "Publication", testo: "The same listing in Italian, English, German and Slovene, with any use of AI on the photos declared photo by photo." },
      { titolo: "Private Collection", testo: "Houses that never go on the portals reach only those who have signed up, through personal access." },
    ],
    tour: "Open the 3D tour", tourSotto: "Matterport · loads on click",
    film: "Watch the film", filmSotto: "Cookie-free YouTube · loads on click",
    pc: "In Trieste, today, 22 reserved houses",
  },
  chiCompra: {
    h3: "The demand is already there, and it writes from far away.",
    colA: "The group · TriesteVillas CRM, last twelve months",
    colB: "The market around the lake · OMI, 2025 sales",
    numA: "1,312", cosaA: "buyers have written to us",
    numB: "4,142", cosaB: "homes sold in the municipalities of the province of Novara, excluding the provincial capital",
    altriA: [["391", "with a budget of €500,000 or more"], ["152", "€1,000,000 or more"], ["105", "from Austria, Germany and Switzerland"], ["262", "asked for a villa or a detached house"]],
    altriB: [["+14.0%", "on 2024, province of Novara"], ["2,251", "in the municipalities of Verbano-Cusio-Ossola, excluding the provincial capital"], ["+10.1%", "on 2024, Verbano-Cusio-Ossola"], ["+3.2%", "median change in OMI price ranges on the lake over one year"]],
    altri: "The other four figures",
    nota: "The CRM enquiries concern houses in and around Trieste, not on Lake Orta; nationality is known for only some of the buyers. Counts as of 5 October 2026, excluding tests, duplicates and spam. Sales: Agenzia delle Entrate, OMI, provisional 2025 volumes (NTN), extracted on 6 October 2026; these are whole provinces, not just the lake.",
    chiusa: "Many of them have never seen Lake Orta. This atlas shows it to them.",
    proprietari: "Own a house on the lake? Here is how we would present it",
  },
  collezione: {
    occhiello: "Private Collection · Lake Orta",
    h2: "The lake's first houses will arrive here, before anywhere else.",
    zero: "In the collection today: 0 houses on the lake. We will write to you when the first one comes in for your areas.",
    trieste: "In Trieste our Private Collection currently holds 22 reserved houses, 15 of them at €1,000,000 or more.",
    triesteLink: "What the Private Collection looks like in Trieste",
    invito: "Leave us an address and the areas you are interested in: we will write when the first house comes in, and not before.",
  },
  gruppo: {
    occhiello: "The group",
    h2: "Behind the atlas, TriesteVillas.",
    lead: "Six websites from the Tagliamento to the Karst, and from today Lake Orta. These are the group's figures, counted in our CRM and on our websites: each one has its source and its date.",
    numeri: [["90", "properties online across the group's four sites"], ["1,312", "buyers wrote to us in twelve months"], ["529", "viewings in twelve months"], ["4.5/5", "on Google, 73 reviews"]],
    marchi: [
      { nome: "TriesteVillas", dove: "Fine homes in Trieste", href: "https://triestevillas.com/" },
      { nome: "TriesteImmobiliare", dove: "Everyday homes", href: "https://triesteimmobiliare.com/" },
      { nome: "TriesteAffitti", dove: "Lettings in Trieste", href: "https://triesteaffitti.com/" },
      { nome: "FriuliVillas", dove: "Villas and houses in Friuli", href: "https://friulivillas.com/" },
      { nome: "LignanoVillas", dove: "Seaside homes in Lignano", href: "https://lignanovillas.com/" },
      { nome: "SloveniaVillas", dove: "Slovenian coast and Karst", href: "https://sloveniavillas.com/" },
    ],
    canale: "The channel · @TriesteVillasImmobiliare", canaleNum: "1,990,369", canaleSotto: "views · 140 videos, since 2015", canaleLink: "The channel on YouTube",
    nota: "Sources: TriesteVillas CRM and the public catalogues of the group's websites, counts as of 5 October 2026; Google and YouTube on the same date.",
  },
  epilogo: {
    occhiello: "Over the hill",
    h2: "Now you know what lies behind the Mottarone.",
    guide: "The guides",
    video: "Real footage · Lake Orta, filmed from a lakeside property",
  },
};

const de: TestiHome = {
  titolo: "OrtaVillas · Der Ortasee, von Mailand aus vermessen",
  descrizione: "Der Ortasee, 67 bis 96 Minuten von der Piazza del Duomo: OSRM-Fahrzeiten, Höhenlagen, Wintersonne, OMI-Preisspannen und die Methode von TriesteVillas. Ausgabe 01, Oktober 2026.",
  coordinate: "Ausgangspunkt der Fahrzeiten · 45.464° N · 9.191° E",
  h1: "Fünfundsiebzig Minuten von Mailand beginnt ein anderer See.",
  nastroDa: "Piazza del Duomo",
  nastroNota: "ohne Verkehr, OSRM",
  ctaPC: "Private Collection: Als Erste informiert werden",
  ctaCarta: "Karte öffnen",
  statoLungo: "Oktober 2026 · Am Ortasee können wir bereits vermitteln: TriesteVillas ist eine in Italien eingetragene Immobilienagentur. Doch heute ist kein einziges Haus vom See in der Sammlung, und das sagen wir offen: erst der Atlas, dann die Häuser.",
  rilievoAlt: "Schattiertes Relief des Ortasees und der umliegenden Berge, vom Mottarone bis zum Valle Strona, mit den sechzehn Orten des Atlas und den Minuten ab Mailand.",
  voloAria: "Der Flug: von der Autobahn zum See, in fünf Einstellungen",
  voloEtichetta: "Der Flug",
  cap: [
    {
      h2: "Die richtige Ausfahrt heißt Borgomanero.",
      corpo: "Von Mailand nehmen Sie die A8 dei Laghi, folgen der Abzweigung Richtung Gattico und verlassen die A26 in Borgomanero: Von dort steigt die Staatsstraße 229 am Ostufer entlang an. Von Malpensa ist es noch näher. Mit dem Zug dagegen gibt es ab Mailand keine Direktverbindung.",
      scheda: [["Mailand Dom → Orta", "75 min · 87 km"], ["Malpensa T1 → Orta", "54 min · 47 km"], ["Orta-Miasino → Mailand mit dem Zug", "1 Std. 33 – 1 Std. 54, Umstieg in Novara"]],
    },
    {
      h2: "Orta San Giulio, 75 Minuten von der Piazza del Duomo.",
      corpo: "Der Ort, die Piazza Motta, der Palazzotto von 1582 und, rund 400 Meter vor dem Ufer, die Insel San Giulio mit ihrer Basilika, die aus einem Oratorium des späten 4. Jahrhunderts hervorging. Dahinter der Sacro Monte, seit 2003 UNESCO-Welterbe. Hier liegen auch die höchsten Preisspannen am See.",
      scheda: [["Orta San Giulio", "75 min · 87 km"], ["Isola di San Giulio", "rund 400 m vor dem Ufer"], ["Villen, Seeufer und Insel", "2.100–3.000 €/m² · OMI, 2. Halbjahr 2025"]],
      lente: { src: "/assets/images/lago-orta-isola-san-giulio-dallalto.jpg", alt: "Die Insel San Giulio von oben, mit Basilika und Glockenturm im grünen Wasser des Sees.", credito: "Echte Aufnahme · Unsplash" },
    },
    {
      h2: "Der See, ohne Auto.",
      corpo: "Von März bis Oktober legen die Linienschiffe der Navigazione Lago d'Orta in Omegna, Orta, auf der Insel, in Pella, Pettenasco und Gozzano an. Am Ostufer verläuft die Bahnlinie Novara–Domodossola, mit fünf Bahnhöfen am See. Im Winter ruht der Linienverkehr auf dem Wasser.",
      scheda: [["Linienschiffe", "März – Oktober · 3 Motorschiffe"], ["Bahnhöfe am See", "Gozzano, Bolzano Novarese, Orta-Miasino, Pettenasco, Omegna"], ["Orta-Miasino → Novara", "8 Züge an einem Beispiel-Mittwoch · 42–53 min"]],
      lente: { src: "/assets/images/pontile-tramonto-lago-orta.jpg", alt: "Ein Holzsteg am Ortasee bei Sonnenuntergang, stilles Wasser und die Berge im Gegenlicht.", credito: "Echte Aufnahme · Unsplash" },
    },
    {
      h2: "Zweihundert Meter höher, zwei Stunden mehr Sonne.",
      corpo: "Oberhalb des Ostufers, am Hang des Mottarone, liegen Ameno, Vacciago, Miasino und Armeno zwischen 478 und 543 Metern. Am 21. Dezember haben Ameno und Vacciago mehr direkte Sonne als jeder andere Ort am See: Der Berg, der in Omegna und am Westufer die Sonne früh verdeckt, steht hier im Rücken. Die Seilbahn von Stresa zum Gipfel ist seit 2021 geschlossen.",
      scheda: [["Direkte Sonne am 21. Dezember", "Ameno 8 Std. 04 · Omegna 5 Std. 37"], ["Letzte Sonne in Ronco, 21. Dezember", "14:06 Uhr"], ["Höhenlagen", "Armeno 543 m · Ameno 531 m · Miasino 478 m"]],
      lente: { src: "/assets/images/panorama-mottarone-lago-orta.jpg", alt: "Wiesen am Mottarone, unten der Ortasee, in der Ferne die Hügel.", credito: "Echte Aufnahme · Unsplash" },
    },
    {
      h2: "Vier Welten in einer halben Stunde.",
      corpo: "Das Ostufer, das Westufer, die Hügel des Mottarone und die beiden Enden des Sees. Von einem Ende zum anderen sind es zwölfeinhalb Kilometer Wasser; jeder Ort hat seine eigene Seite, mit Fahrzeiten, Höhenlage, Sonne und Preisspannen.",
      scheda: [],
    },
  ],
  mondiTitolo: "Die vier Welten",
  luoghiTitolo: "Die sechzehn Orte, der nächste zu Mailand zuerst",
  mondiNota: "Die Grenzen der Welten sind ungefähr und von uns gezogen.",
  esplora: "Orte entdecken",
  daCasa: {
    occhiello: "Von Ihrer Haustür",
    h2: "Wo fahren Sie los?",
    lead: "Wählen Sie Ihre Ausgangsstadt: Die Zeiten folgen der echten Straße, mit dem Unterschied zu Mailand. Drei Fragen, und die Karte reiht die drei Orte auf, die am besten zu Ihnen passen.",
    tuttiTempi: "Alle Fahrzeiten: Ort für Ort und die vollständige Tabelle",
    tabellaTitolo: "Fahrzeiten mit dem Auto, Ort für Ort",
    colonne: ["Ort", "Welt", "Fahrzeit", "Kilometer"],
    nota: "OSRM ohne Verkehr, gemessen am 6. Oktober 2026. Staus, Baustellen, Maut und Kontrollen an der Schweizer Grenze sind nicht berücksichtigt: Im Sommer und an Wochenenden dauert die Fahrt länger.",
    tutteDistanze: "Alle Entfernungen",
    rispetto: "im Vergleich zu Mailand",
    riferimento: "Bezugspunkt",
  },
  metodo: {
    occhiello: "Die Methode",
    h2: "Wie ein Haus einen Käufer in Zürich erreicht.",
    lead: "Bevor wir ein Haus beschreiben, studieren wir es. Am Ortasee haben wir noch keinen öffentlichen Fall: Hier sehen Sie unsere tägliche Methode in Triest, an einem echten Haus.",
    caso: "Der Fall: Villa storica Strada Costiera, auf triestevillas.com · TSV-PROP-0003",
    passi: [
      { titolo: "Analyse", testo: "Unterlagen, Kataster, Konformität und Vergleichswerte aus der Umgebung. Bevor wir eine Zeile schreiben, wissen wir, was wir vorstellen, Schwachpunkte inbegriffen." },
      { titolo: "Aufnahme", testo: "Fotos, Grundriss und 3D-Rundgang: Das Haus lässt sich von Zürich aus besichtigen, bevor sich jemand auf den Weg macht." },
      { titolo: "Erzählung", testo: "Texte in vier Sprachen und ein Film über das Haus, mit offen benannten Grenzen." },
      { titolo: "Veröffentlichung", testo: "Dasselbe Exposé auf Italienisch, Englisch, Deutsch und Slowenisch; der Einsatz von KI an den Fotos ist Bild für Bild angegeben." },
      { titolo: "Private Collection", testo: "Häuser, die nie auf die Portale gehen, erreichen nur, wer sich eingetragen hat, mit persönlichem Zugang." },
    ],
    tour: "3D-Rundgang öffnen", tourSotto: "Matterport · lädt erst beim Klick",
    film: "Film ansehen", filmSotto: "YouTube ohne Cookies · lädt erst beim Klick",
    pc: "In Triest heute 22 vertrauliche Häuser",
  },
  chiCompra: {
    h3: "Die Nachfrage ist schon da, und sie schreibt aus der Ferne.",
    colA: "Die Gruppe · CRM TriesteVillas, letzte zwölf Monate",
    colB: "Der Markt rund um den See · OMI, Verkäufe 2025",
    numA: "1.312", cosaA: "Käufer haben uns geschrieben",
    numB: "4.142", cosaB: "verkaufte Wohnimmobilien in den Gemeinden der Provinz Novara, ohne die Provinzhauptstadt",
    altriA: [["391", "mit einem Budget ab 500.000 €"], ["152", "ab 1.000.000 €"], ["105", "aus Österreich, Deutschland und der Schweiz"], ["262", "fragten nach einer Villa oder einem freistehenden Haus"]],
    altriB: [["+14,0 %", "gegenüber 2024, Provinz Novara"], ["2.251", "in den Gemeinden des Verbano-Cusio-Ossola, ohne die Provinzhauptstadt"], ["+10,1 %", "gegenüber 2024, Verbano-Cusio-Ossola"], ["+3,2 %", "Median der Veränderung der OMI-Preisspannen am See binnen eines Jahres"]],
    altri: "Die anderen vier Zahlen",
    nota: "Die Anfragen im CRM betreffen Häuser in und um Triest, nicht am Ortasee; die Nationalität ist nur für einen Teil der Käufer bekannt. Stand der Zählung: 5. Oktober 2026, ohne Tests, Dubletten und Spam. Verkäufe: Agenzia delle Entrate, OMI, vorläufige Volumen 2025 (NTN), abgerufen am 6. Oktober 2026; es handelt sich um ganze Provinzen, nicht nur um den See.",
    chiusa: "Viele von ihnen haben den Ortasee nie gesehen. Dieser Atlas zeigt ihn ihnen.",
    proprietari: "Sie besitzen ein Haus am See? So würden wir es vorstellen",
  },
  collezione: {
    occhiello: "Private Collection · Ortasee",
    h2: "Die ersten Häuser vom See kommen hierher, früher als anderswo.",
    zero: "Heute in der Sammlung: 0 Häuser vom See. Wir schreiben Ihnen, sobald das erste in Ihren Gegenden hinzukommt.",
    trieste: "In Triest umfasst unsere Private Collection heute 22 vertrauliche Häuser, 15 davon ab 1.000.000 €.",
    triesteLink: "So sieht die Private Collection in Triest aus",
    invito: "Hinterlassen Sie uns eine Adresse und die Gegenden, die Sie interessieren: Wir schreiben Ihnen, wenn das erste Haus hinzukommt, und nicht vorher.",
  },
  gruppo: {
    occhiello: "Die Gruppe",
    h2: "Hinter dem Atlas steht TriesteVillas.",
    lead: "Sechs Websites vom Tagliamento bis zum Karst, und ab heute der Ortasee. Das sind die Zahlen der Gruppe, gezählt in unserem CRM und auf unseren Websites: Jede hat ihre Quelle und ihr Datum.",
    numeri: [["90", "Immobilien online auf den vier Websites der Gruppe"], ["1.312", "Käufer haben uns in zwölf Monaten geschrieben"], ["529", "Besichtigungen in zwölf Monaten"], ["4,5/5", "auf Google, 73 Bewertungen"]],
    marchi: [
      { nome: "TriesteVillas", dove: "Exklusive Häuser in Triest", href: "https://triestevillas.com/" },
      { nome: "TriesteImmobiliare", dove: "Häuser für jeden Tag", href: "https://triesteimmobiliare.com/" },
      { nome: "TriesteAffitti", dove: "Mieten in Triest", href: "https://triesteaffitti.com/" },
      { nome: "FriuliVillas", dove: "Villen und Häuser im Friaul", href: "https://friulivillas.com/" },
      { nome: "LignanoVillas", dove: "Häuser am Meer in Lignano", href: "https://lignanovillas.com/" },
      { nome: "SloveniaVillas", dove: "Slowenische Küste und Karst", href: "https://sloveniavillas.com/" },
    ],
    canale: "Der Kanal · @TriesteVillasImmobiliare", canaleNum: "1.990.369", canaleSotto: "Aufrufe · 140 Videos, seit 2015", canaleLink: "Der Kanal auf YouTube",
    nota: "Quellen: CRM TriesteVillas und öffentliche Kataloge der Websites der Gruppe, Stand 5. Oktober 2026; Google und YouTube zum selben Datum.",
  },
  epilogo: {
    occhiello: "Auf der anderen Seite des Hügels",
    h2: "Jetzt wissen Sie, was hinter dem Mottarone liegt.",
    guide: "Die Ratgeber",
    video: "Echte Aufnahme · Ortasee, gefilmt von einem Anwesen am See",
  },
};

// Sloveno: vikanje, «jezero Orta», spazio unificatore ( ) prima di € e % (guida-sloveno.md § 6).
const sl: TestiHome = {
  titolo: "OrtaVillas · Jezero Orta, izmerjeno iz Milana",
  descrizione: "Jezero Orta od 67 do 96 minut od Piazze del Duomo: časi vožnje OSRM, nadmorske višine, zimsko sonce, cene OMI in metoda TriesteVillas. Izdaja 01, oktober 2026.",
  coordinate: "Izhodišče časov vožnje · 45.464° N · 9.191° E",
  h1: "Petinsedemdeset minut od Milana se začne drugo jezero.",
  nastroDa: "Piazza del Duomo",
  nastroNota: "brez prometa, OSRM",
  ctaPC: "Private Collection: obvestite me med prvimi",
  ctaCarta: "Odprite zemljevid",
  statoLungo: "Oktober 2026 · Na jezeru Orta že lahko posredujemo: TriesteVillas je v Italiji registrirana nepremičninska agencija. A danes v zbirki ni še nobene hiše ob jezeru, in to tudi povemo: najprej atlas, nato hiše.",
  rilievoAlt: "Senčen relief jezera Orta in okoliških gora, od Mottarona do doline Valle Strona, s šestnajstimi kraji atlasa in minutami od Milana.",
  voloAria: "Let: od avtoceste do jezera, v petih kadrih",
  voloEtichetta: "Let",
  cap: [
    {
      h2: "Prava izvoznica je Borgomanero.",
      corpo: "Iz Milana zapeljete na avtocesto A8 dei Laghi, nadaljujete po odcepu proti Gatticu in zapustite A26 pri Borgomaneru: od tam se državna cesta 229 vzpenja ob vzhodni obali. Z letališča Malpensa je še bliže. Z vlakom pa iz Milana ni neposredne povezave.",
      scheda: [["Milano, Duomo → Orta", "75 min · 87 km"], ["Malpensa T1 → Orta", "54 min · 47 km"], ["Orta-Miasino → Milano z vlakom", "1 h 33 – 1 h 54, prestop v Novari"]],
    },
    {
      h2: "Orta San Giulio, 75 minut od Piazze del Duomo.",
      corpo: "Staro jedro, trg Piazza Motta, Palazzotto iz leta 1582 in, približno 400 metrov od obale, otok San Giulio z baziliko, ki je zrasla iz oratorija s konca 4. stoletja. Zadaj Sacro Monte, od leta 2003 na Unescovem seznamu svetovne dediščine. Tu so tudi najvišje cene ob jezeru.",
      scheda: [["Orta San Giulio", "75 min · 87 km"], ["Otok San Giulio", "približno 400 m od obale"], ["Vile, obala in otok", "2.100–3.000 €/m² · OMI, 2. polletje 2025"]],
      lente: { src: "/assets/images/lago-orta-isola-san-giulio-dallalto.jpg", alt: "Otok San Giulio od zgoraj, z baziliko in zvonikom sredi zelene vode jezera.", credito: "Resničen posnetek · Unsplash" },
    },
    {
      h2: "Jezero brez avtomobila.",
      corpo: "Od marca do oktobra redne ladje družbe Navigazione Lago d'Orta pristajajo v Omegni, Orti, na otoku, v Pelli, Pettenascu in Gozzanu. Ob vzhodni obali poteka železniška proga Novara–Domodossola s petimi postajami ob jezeru. Pozimi redna ladijska linija ne vozi.",
      scheda: [["Redne ladijske linije", "marec – oktober · 3 motorne ladje"], ["Postaje ob jezeru", "Gozzano, Bolzano Novarese, Orta-Miasino, Pettenasco, Omegna"], ["Orta-Miasino → Novara", "8 vlakov na vzorčno sredo · 42–53 min"]],
      lente: { src: "/assets/images/pontile-tramonto-lago-orta.jpg", alt: "Lesen pomol na jezeru Orta ob sončnem zahodu, z mirno vodo in gorami v protisvetlobi.", credito: "Resničen posnetek · Unsplash" },
    },
    {
      h2: "Dvesto metrov višje, dve uri sonca več.",
      corpo: "Nad vzhodno obalo, na pobočju Mottarona, ležijo Ameno, Vacciago, Miasino in Armeno med 478 in 543 metri. Na dan 21. decembra imata Ameno in Vacciago največ neposrednega sonca ob vsem jezeru: gora, ki v Omegni in na zahodni obali sonce zgodaj zakrije, je tu za hrbtom. Žičnica iz Strese na vrh je zaprta od leta 2021.",
      scheda: [["Neposredno sonce 21. decembra", "Ameno 8 h 04 · Omegna 5 h 37"], ["Zadnje sonce v Roncu, 21. decembra", "14.06"], ["Nadmorske višine", "Armeno 543 m · Ameno 531 m · Miasino 478 m"]],
      lente: { src: "/assets/images/panorama-mottarone-lago-orta.jpg", alt: "Travniki na Mottaronu, spodaj jezero Orta, v daljavi griči.", credito: "Resničen posnetek · Unsplash" },
    },
    {
      h2: "Štirje svetovi v pol ure.",
      corpo: "Vzhodna obala, zahodna obala, griči Mottarona in oba konca jezera. Od enega konca do drugega je dvanajst kilometrov in pol vode; vsak kraj ima svojo stran s časi vožnje, nadmorsko višino, soncem in cenami.",
      scheda: [],
    },
  ],
  mondiTitolo: "Štirje svetovi",
  luoghiTitolo: "Šestnajst krajev, od najbližjega Milanu",
  mondiNota: "Meje svetov so okvirne, zarisali smo jih sami.",
  esplora: "Raziščite kraje",
  daCasa: {
    occhiello: "Od vašega doma",
    h2: "Od kod se odpravljate?",
    lead: "Izberite mesto odhoda: časi sledijo pravi cesti, z razliko glede na Milano. Tri vprašanja in zemljevid razvrsti tri kraje, ki so vam najbolj podobni.",
    tuttiTempi: "Vsi časi: kraj za krajem in celotna preglednica",
    tabellaTitolo: "Časi vožnje z avtomobilom, kraj za krajem",
    colonne: ["Kraj", "Svet", "Čas vožnje", "Kilometri"],
    nota: "OSRM brez prometa, izmerjeno 6. oktobra 2026. Niso upoštevani zastoji, gradbišča, cestnine in kontrole na švicarski meji: poleti in ob koncih tedna so dejanski časi daljši.",
    tutteDistanze: "Vse razdalje",
    rispetto: "glede na Milano",
    riferimento: "izhodišče",
  },
  metodo: {
    occhiello: "Metoda",
    h2: "Kako hiša pride do kupca iz Züricha.",
    lead: "Preden hišo predstavimo, jo preučimo. Na jezeru Orta še nimamo javnega primera: spodaj je metoda, po kateri vsak dan delamo v Trstu, na resnični hiši.",
    caso: "Primer: Villa storica Strada Costiera, na triestevillas.com · TSV-PROP-0003",
    passi: [
      { titolo: "Analiza", testo: "Dokumentacija, kataster, skladnost in cene v bližini. Preden napišemo eno vrstico, vemo, kaj predstavljamo, tudi šibke točke." },
      { titolo: "Snemanje", testo: "Fotografije, tloris in 3D-ogled: hišo si lahko ogledate iz Züricha, preden se kdor koli odpravi na pot." },
      { titolo: "Pripoved", testo: "Besedila v štirih jezikih in film o hiši, z jasno povedanimi omejitvami." },
      { titolo: "Objava", testo: "Ista predstavitev v italijanščini, angleščini, nemščini in slovenščini; uporaba umetne inteligence na fotografijah je navedena pri vsaki fotografiji posebej." },
      { titolo: "Private Collection", testo: "Hiše, ki ne gredo na portale, prejmejo le tisti, ki so se prijavili, z osebnim dostopom." },
    ],
    tour: "Odprite 3D-ogled", tourSotto: "Matterport · naloži se ob kliku",
    film: "Oglejte si film", filmSotto: "YouTube brez piškotkov · naloži se ob kliku",
    pc: "V Trstu danes 22 hiš izven javnega trga",
  },
  chiCompra: {
    h3: "Povpraševanje že obstaja, in piše od daleč.",
    colA: "Skupina · CRM TriesteVillas, zadnjih dvanajst mesecev",
    colB: "Trg okoli jezera · OMI, prodaje 2025",
    numA: "1.312", cosaA: "kupcev nam je pisalo",
    numB: "4.142", cosaB: "prodanih stanovanjskih nepremičnin v občinah pokrajine Novara, brez glavnega mesta pokrajine",
    altriA: [["391", "s proračunom od 500.000 € naprej"], ["152", "od 1.000.000 € naprej"], ["105", "iz Avstrije, Nemčije in Švice"], ["262", "jih je iskalo vilo ali samostojno hišo"]],
    altriB: [["+14,0 %", "glede na leto 2024, pokrajina Novara"], ["2.251", "v občinah pokrajine Verbano-Cusio-Ossola, brez glavnega mesta pokrajine"], ["+10,1 %", "glede na leto 2024, Verbano-Cusio-Ossola"], ["+3,2 %", "mediana spremembe cen OMI ob jezeru v enem letu"]],
    altri: "Druge štiri številke",
    nota: "Povpraševanja v CRM se nanašajo na hiše v Trstu in okolici, ne ob jezeru Orta; državljanstvo poznamo le za del kupcev. Stanje 5. oktobra 2026, brez preizkusov, dvojnikov in neželene pošte. Prodaje: Agenzia delle Entrate, OMI, začasni podatki za leto 2025 (NTN), pridobljeni 6. oktobra 2026; gre za celotne pokrajine, ne le za jezero.",
    chiusa: "Mnogi med njimi jezera Orta še niso videli. Ta atlas jim ga pokaže.",
    proprietari: "Imate hišo ob jezeru? Tako bi jo predstavili",
  },
  collezione: {
    occhiello: "Private Collection · jezero Orta",
    h2: "Prve hiše ob jezeru bodo prišle sem, prej kot drugam.",
    zero: "Danes v zbirki: 0 hiš ob jezeru. Pisali vam bomo, ko se bo na vaših območjih pojavila prva.",
    trieste: "V Trstu naša Private Collection danes šteje 22 hiš izven javnega trga, od tega 15 od 1.000.000 € naprej.",
    triesteLink: "Kakšna je Private Collection v Trstu",
    invito: "Pustite nam naslov in območja, ki vas zanimajo: pisali vam bomo, ko pride prva hiša, in ne prej.",
  },
  gruppo: {
    occhiello: "Skupina",
    h2: "Za atlasom stoji TriesteVillas.",
    lead: "Šest spletnih strani od Tilmenta do Krasa, od danes pa še jezero Orta. To so številke skupine, preštete v našem CRM in na naših straneh: vsaka ima svoj vir in svoj datum.",
    numeri: [["90", "nepremičnin na spletu na štirih straneh skupine"], ["1.312", "kupcev nam je pisalo v dvanajstih mesecih"], ["529", "ogledov v dvanajstih mesecih"], ["4,5/5", "na Googlu, 73 ocen"]],
    marchi: [
      { nome: "TriesteVillas", dove: "Prestižne nepremičnine v Trstu", href: "https://triestevillas.com/" },
      { nome: "TriesteImmobiliare", dove: "Nepremičnine za vsak dan", href: "https://triesteimmobiliare.com/" },
      { nome: "TriesteAffitti", dove: "Najem v Trstu", href: "https://triesteaffitti.com/" },
      { nome: "FriuliVillas", dove: "Vile in hiše v Furlaniji", href: "https://friulivillas.com/" },
      { nome: "LignanoVillas", dove: "Hiše ob morju v Lignanu", href: "https://lignanovillas.com/" },
      { nome: "SloveniaVillas", dove: "Slovenska obala in Kras", href: "https://sloveniavillas.com/" },
    ],
    canale: "Kanal · @TriesteVillasImmobiliare", canaleNum: "1.990.369", canaleSotto: "ogledov · 140 videov, od leta 2015", canaleLink: "Kanal na YouTubu",
    nota: "Viri: CRM TriesteVillas in javni katalogi spletnih strani skupine, stanje 5. oktobra 2026; Google in YouTube na isti dan.",
  },
  epilogo: {
    occhiello: "Na drugi strani hriba",
    h2: "Zdaj veste, kaj je za Mottaronom.",
    guide: "Vodniki",
    video: "Resničen posnetek · jezero Orta, posneto s posestva ob jezeru",
  },
};

export const HOME: Record<Lingua, TestiHome> = { it, en, de, sl };
