import type { Lingua } from "@/lib/rotte";
import type { LuogoUI, TestiSestante } from "@/components/Sestante";

const ore = (min: number, h: string, m: string) => `${Math.floor(min / 60)} ${h} ${String(min % 60).padStart(2, "0")} ${m}`;
const t = (min: number, l: Lingua) => {
  const u = l === "de" ? ["Std.", "Min."] : ["h", "min"];
  return min < 90 ? `${min} ${u[1]}` : ore(min, u[0], u[1]);
};

export const TESTI_SESTANTE: Record<Lingua, TestiSestante> = {
  it: {
    da: "Da dove arrivate?",
    acqua: "L'acqua a piedi o la collina aperta?",
    acquaSegni: ["l'acqua a piedi", "la collina aperta"],
    acquaValori: ["l'acqua a piedi", "vicino all'acqua", "a metà costa", "verso la collina", "la collina aperta"],
    acquaAiuto: "Misuriamo i metri sopra il pelo del lago (290 m) al centro di ogni luogo: dai 9 m di Orta ai 554 m di Quarna Sopra.",
    budget: "Il vostro budget",
    budgetValori: ["fino a 500.000 €", "500.000 € – 1.000.000 €", "1.000.000 € – 2.000.000 €", "oltre 2.000.000 €"],
    nonSo: "non lo so ancora",
    budgetAiuto: "In Italia i prezzi delle singole compravendite non sono pubblici: confrontiamo la fascia con il livello delle quotazioni OMI del comune (ville, zona più cara). Non premia il luogo più economico.",
    sole: "Il sole d'inverno",
    soleValori: ["non conta", "conta", "è essenziale"],
    soleAiuto: "Minuti di sole diretto il 21 dicembre, calcolati da noi sul rilievo: conta solo la montagna, non gli edifici né gli alberi.",
    ritmo: "Cittadina o silenzio?",
    ritmoValori: ["cittadina", "borgo vivo", "a metà", "paese", "silenzio"],
    indifferente: "indifferente",
    ritmoAiuto: "Lo misuriamo con gli abitanti (ISTAT, 1° gennaio 2025): dai 14.185 di Omegna ai 242 di Quarna Sopra.",
    vicino: "Che cosa vi serve vicino?",
    viciniValori: { stazione: "una stazione", battello: "il battello di linea", malpensa: "Malpensa" },
    vicinoAiuto: "Stazione e imbarcadero in linea d'aria dal centro; Malpensa in minuti d'auto senza traffico. I battelli di linea girano da marzo a ottobre.",
    carta: "La vostra carta",
    partenza: "partenza:",
    primo: (a, b, c) => `Primo ${a}, secondo ${b}, terzo ${c}.`,
    su100: "su 100",
    su100Title: "Quanto il luogo corrisponde alle vostre risposte, da 0 a 100",
    motivi: {
      tempo: (v) => `${t(v, "it")} in auto da casa vostra`,
      quota: (v) => (v < 30 ? `a ${v} m sopra il lago, l'acqua a due passi` : `a ${v} m sopra il pelo del lago`),
      budget: (v) => `ville fino a ${v.toLocaleString("it-IT")} €/m² nella zona più cara (OMI)`,
      sole: (v) => `${ore(v, "h", "min")} di sole diretto il 21 dicembre`,
      ritmo: (v) => (v >= 5000 ? `una cittadina di ${v.toLocaleString("it-IT")} abitanti, i servizi a piedi` : v > 200 ? `${v.toLocaleString("it-IT")} abitanti` : "una frazione, poche case"),
      stazione: (v) => `stazione a ${v.toLocaleString("it-IT")} km in linea d'aria`,
      battello: (v) => (v < 0.2 ? "l'imbarcadero è in paese" : `imbarcadero a ${v.toLocaleString("it-IT")} km`),
      malpensa: (v) => `${t(v, "it")} da Malpensa`,
    },
    avvisami: "Avvisatemi per queste zone",
    copia: "Copia il link della vostra carta",
    copiato: "Link copiato",
    soloRisposte: "Il link contiene solo le vostre risposte, nessun dato personale.",
    completa: "Apri la carta completa, con sei domande",
    tutti: "Tutti i 16 luoghi",
  },
  en: {
    da: "Where are you coming from?",
    acqua: "Water on foot or open hillside?",
    acquaSegni: ["water on foot", "open hillside"],
    acquaValori: ["water on foot", "near the water", "halfway up", "towards the hills", "open hillside"],
    acquaAiuto: "We measure metres above the lake surface (290 m) at the centre of each place: from 9 m in Orta to 554 m in Quarna Sopra.",
    budget: "Your budget",
    budgetValori: ["up to €500,000", "€500,000 – €1,000,000", "€1,000,000 – €2,000,000", "over €2,000,000"],
    nonSo: "not sure yet",
    budgetAiuto: "In Italy individual sale prices are not public: we compare your band with the level of the municipality's OMI quotations (villas, most expensive zone). It does not reward the cheapest place.",
    sole: "Winter sun",
    soleValori: ["does not matter", "matters", "essential"],
    soleAiuto: "Minutes of direct sun on 21 December, calculated by us from the terrain: only the mountains count, not buildings or trees.",
    ritmo: "Small town or silence?",
    ritmoValori: ["small town", "lively village", "in between", "village", "silence"],
    indifferente: "no preference",
    ritmoAiuto: "Measured by population (ISTAT, 1 January 2025): from 14,185 in Omegna to 242 in Quarna Sopra.",
    vicino: "What do you need nearby?",
    viciniValori: { stazione: "a railway station", battello: "the scheduled boat", malpensa: "Malpensa" },
    vicinoAiuto: "Station and pier as the crow flies from the centre; Malpensa in driving minutes without traffic. Scheduled boats run from March to October.",
    carta: "Your map",
    partenza: "starting from:",
    primo: (a, b, c) => `First ${a}, second ${b}, third ${c}.`,
    su100: "of 100",
    su100Title: "How well the place matches your answers, from 0 to 100",
    motivi: {
      tempo: (v) => `${t(v, "en")} by car from your home`,
      quota: (v) => (v < 30 ? `${v} m above the lake, the water a few steps away` : `${v} m above the lake surface`),
      budget: (v) => `villas up to €${v.toLocaleString("en-GB")}/m² in the most expensive zone (OMI)`,
      sole: (v) => `${ore(v, "h", "min")} of direct sun on 21 December`,
      ritmo: (v) => (v >= 5000 ? `a town of ${v.toLocaleString("en-GB")} people, services on foot` : v > 200 ? `${v.toLocaleString("en-GB")} residents` : "a hamlet, a few houses"),
      stazione: (v) => `station ${v.toLocaleString("en-GB")} km as the crow flies`,
      battello: (v) => (v < 0.2 ? "the pier is in the village" : `pier ${v.toLocaleString("en-GB")} km away`),
      malpensa: (v) => `${t(v, "en")} from Malpensa`,
    },
    avvisami: "Tell me about these areas",
    copia: "Copy the link to your map",
    copiato: "Link copied",
    soloRisposte: "The link contains only your answers, no personal data.",
    completa: "Open the full map, with six questions",
    tutti: "All 16 places",
  },
  de: {
    da: "Woher kommen Sie?",
    acqua: "Das Wasser zu Fuß oder der offene Hang?",
    acquaSegni: ["Wasser zu Fuß", "offener Hang"],
    acquaValori: ["Wasser zu Fuß", "nahe am Wasser", "auf halber Höhe", "Richtung Hügel", "offener Hang"],
    acquaAiuto: "Wir messen die Meter über dem Seespiegel (290 m) im Zentrum jedes Ortes: von 9 m in Orta bis 554 m in Quarna Sopra.",
    budget: "Ihr Budget",
    budgetValori: ["bis 500.000 €", "500.000 € – 1.000.000 €", "1.000.000 € – 2.000.000 €", "über 2.000.000 €"],
    nonSo: "weiß ich noch nicht",
    budgetAiuto: "In Italien sind die Preise einzelner Verkäufe nicht öffentlich: Wir vergleichen Ihre Spanne mit dem Niveau der OMI-Richtwerte der Gemeinde (Villen, teuerste Zone). Der billigste Ort wird nicht bevorzugt.",
    sole: "Wintersonne",
    soleValori: ["egal", "wichtig", "unverzichtbar"],
    soleAiuto: "Minuten direkter Sonne am 21. Dezember, von uns aus dem Gelände berechnet: Es zählen nur die Berge, weder Gebäude noch Bäume.",
    ritmo: "Kleinstadt oder Stille?",
    ritmoValori: ["Kleinstadt", "lebhaftes Dorf", "dazwischen", "Dorf", "Stille"],
    indifferente: "egal",
    ritmoAiuto: "Gemessen an der Einwohnerzahl (ISTAT, 1. Januar 2025): von 14.185 in Omegna bis 242 in Quarna Sopra.",
    vicino: "Was brauchen Sie in der Nähe?",
    viciniValori: { stazione: "einen Bahnhof", battello: "das Linienschiff", malpensa: "Malpensa" },
    vicinoAiuto: "Bahnhof und Anlegestelle in Luftlinie vom Zentrum; Malpensa in Fahrminuten ohne Verkehr. Die Linienschiffe fahren von März bis Oktober.",
    carta: "Ihre Karte",
    partenza: "Start:",
    primo: (a, b, c) => `Erstens ${a}, zweitens ${b}, drittens ${c}.`,
    su100: "von 100",
    su100Title: "Wie gut der Ort zu Ihren Antworten passt, von 0 bis 100",
    motivi: {
      tempo: (v) => `${t(v, "de")} mit dem Auto von zu Hause`,
      quota: (v) => (v < 30 ? `${v} m über dem See, das Wasser ein paar Schritte entfernt` : `${v} m über dem Seespiegel`),
      budget: (v) => `Villen bis ${v.toLocaleString("de-DE")} €/m² in der teuersten Zone (OMI)`,
      sole: (v) => `${ore(v, "Std.", "Min.")} direkte Sonne am 21. Dezember`,
      ritmo: (v) => (v >= 5000 ? `eine Kleinstadt mit ${v.toLocaleString("de-DE")} Einwohnern, alles zu Fuß` : v > 200 ? `${v.toLocaleString("de-DE")} Einwohner` : "ein Weiler, wenige Häuser"),
      stazione: (v) => `Bahnhof ${v.toLocaleString("de-DE")} km Luftlinie`,
      battello: (v) => (v < 0.2 ? "die Anlegestelle ist im Ort" : `Anlegestelle ${v.toLocaleString("de-DE")} km entfernt`),
      malpensa: (v) => `${t(v, "de")} von Malpensa`,
    },
    avvisami: "Benachrichtigen Sie mich für diese Gegenden",
    copia: "Link zu Ihrer Karte kopieren",
    copiato: "Link kopiert",
    soloRisposte: "Der Link enthält nur Ihre Antworten, keine persönlichen Daten.",
    completa: "Die vollständige Karte öffnen, mit sechs Fragen",
    tutti: "Alle 16 Orte",
  },
  sl: {
    da: "Od kod prihajate?",
    acqua: "Voda peš ali odprto pobočje?",
    acquaSegni: ["voda peš", "odprto pobočje"],
    acquaValori: ["voda peš", "blizu vode", "na pol pobočja", "proti gričem", "odprto pobočje"],
    acquaAiuto: "Merimo metre nad gladino jezera (290 m) v središču vsakega kraja: od 9 m v Orti do 554 m v Quarni Sopra.",
    budget: "Vaš proračun",
    budgetValori: ["do 500.000 €", "500.000 € – 1.000.000 €", "1.000.000 € – 2.000.000 €", "nad 2.000.000 €"],
    nonSo: "še ne vem",
    budgetAiuto: "V Italiji cene posameznih prodaj niso javne: vaš razpon primerjamo z ravnjo ocen OMI v občini (vile, najdražja cona). Najcenejši kraj ni nagrajen.",
    sole: "Zimsko sonce",
    soleValori: ["ni pomembno", "je pomembno", "je nujno"],
    soleAiuto: "Minute neposrednega sonca 21. decembra, ki smo jih izračunali iz reliefa: štejejo samo gore, ne stavbe ne drevesa.",
    ritmo: "Mestece ali tišina?",
    ritmoValori: ["mestece", "živahna vas", "nekje vmes", "vas", "tišina"],
    indifferente: "vseeno",
    ritmoAiuto: "Merimo s številom prebivalcev (ISTAT, 1. januar 2025): od 14.185 v Omegni do 242 v Quarni Sopra.",
    vicino: "Kaj potrebujete v bližini?",
    viciniValori: { stazione: "železniško postajo", battello: "redno ladjo", malpensa: "Malpenso" },
    vicinoAiuto: "Postaja in pristan zračne razdalje od središča; Malpensa v minutah vožnje brez prometa. Redne ladje vozijo od marca do oktobra.",
    carta: "Vaš zemljevid",
    partenza: "izhodišče:",
    primo: (a, b, c) => `Prvi ${a}, drugi ${b}, tretji ${c}.`,
    su100: "od 100",
    su100Title: "Kako dobro kraj ustreza vašim odgovorom, od 0 do 100",
    motivi: {
      tempo: (v) => `${t(v, "sl")} z avtom od doma`,
      quota: (v) => (v < 30 ? `${v} m nad jezerom, voda le nekaj korakov stran` : `${v} m nad gladino jezera`),
      budget: (v) => `vile do ${v.toLocaleString("sl-SI")} €/m² v najdražji coni (OMI)`,
      sole: (v) => `${ore(v, "h", "min")} neposrednega sonca 21. decembra`,
      ritmo: (v) => (v >= 5000 ? `mestece s ${v.toLocaleString("sl-SI")} prebivalci, vse peš` : v > 200 ? `${v.toLocaleString("sl-SI")} prebivalcev` : "zaselek, nekaj hiš"),
      stazione: (v) => `postaja ${v.toLocaleString("sl-SI")} km zračne razdalje`,
      battello: (v) => (v < 0.2 ? "pristan je v kraju" : `pristan ${v.toLocaleString("sl-SI")} km stran`),
      malpensa: (v) => `${t(v, "sl")} od Malpense`,
    },
    avvisami: "Obvestite me za ta območja",
    copia: "Kopirajte povezavo do svojega zemljevida",
    copiato: "Povezava kopirana",
    soloRisposte: "Povezava vsebuje samo vaše odgovore, nobenih osebnih podatkov.",
    completa: "Odprite celoten zemljevid, s šestimi vprašanji",
    tutti: "Vseh 16 krajev",
  },
};
export type { LuogoUI };
